### ISSUE TITLE
CROP_CENTER image

### ISSUE THREAD

**Issue by newstarbka** [chrisbanes/PhotoView#123]
Hi, I want to set photoview is CROP_CENTER to display full width( because my image's height is longer than width). But it's display the center of image in screen. So, what sould I do if i want to display from start of image.
Thanks

**Comment by jjhesk** [comment]
I found a piece of code in [here](https://github.com/chrisbanes/PhotoView/blob/48427bff9bb1a408cfebf6697aa019c0788ded76/library/src/main/java/uk/co/senab/photoview/PhotoViewAttacher.java) 

```java
 public void setScale(float scale, float focalX, float focalY, boolean animate) ;
```

I want do the similar effect to scale image to fit the screen width while the minimum scale is still using the original 1.0f is that a way to calculate the CENTER_CROP and the focal?

**Comment by jjhesk** [comment]
eventually i have done something like this 
```java
  pica.load(image_url).into(mImage, new Callback() {
            @Override
            public void onSuccess() {
                mAttacher = new PhotoViewAttacher(mImage);
                mAttacher.setOnMatrixChangeListener(new MatrixChangeListener());
                mAttacher.setOnPhotoTapListener(new PhotoTapListener());
                circle.setVisibility(View.GONE);


                mImage.post(new Runnable() {
                    @Override
                    public void run() {
                        mAttacher.setScale(2f, mImage.getWidth() / 2, mImage.getHeight() / 2, true);
                    }
                });

                //slidrInf.unlock();
                mAttacher.setScale(1.5f);

            }

            @Override
            public void onError() {
                circle.setVisibility(View.GONE);
            }
        });
```

and it works.

**Comment by smarek** [comment]
Consider this workaround as fix, thank you @jjhesk
