### ISSUE TITLE
java.lang.IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by Saklhc** [chrisbanes/PhotoView#206]
java.lang.IllegalArgumentException: pointerIndex out of range

**Comment by smarek** [comment]
Solution is to use `HackyViewPager`

**Comment by rahul-a** [comment]
The HackyViewPager doesn't give a smooth effect in my experience though just a little tweak makes wonders instead of catching IllegalArgumentException in onInterceptTouchEvent() if we catch it in the call to super's onTouchEvent() everything remains butter smooth.

**Comment by ashwindmk** [comment]
1. Downlaod HackyViewPager.java to your project from:
https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/uk/co/senab/photoview/sample/HackyViewPager.java

2. Replace your <android.support.v4.view.ViewPager ... /> with <com.yourpackage.HackyViewPager ... />

3. Typecast ViewPager mPager = (HackyViewPager) mView.findViewById(R.id. ... ); in your activity or fragment.

Done!
