### ISSUE TITLE
A Jar file would be nice

### ISSUE THREAD

**Issue by ameyp** [chrisbanes/PhotoView#207]
Having no experience with gradle, I ran `gradlew` from the root folder and `..\gradlew assembleRelease` from the `library` folder, and I ended up with a library-1.2.3.aar file. Is there an existing way of building a jar?

**Comment by smarek** [comment]
JAR is published on Maven (both releases on central, and snapshots on nexus repositories)
See:
https://oss.sonatype.org/content/groups/public/com/github/chrisbanes/photoview/
https://oss.sonatype.org/content/repositories/snapshots/com/github/chrisbanes/photoview/
