### ISSUE TITLE
Animate ScaleType

### ISSUE THREAD

**Issue by tom91136** [chrisbanes/PhotoView#210]
Is there a way to animate the scale when `setScaleType(...)`? 
For example:
If PhotoView currently has ScaleType.CENTER_INSIDE, doing `setScaleType(ScaleType.CENTER_CROP)` would animate the scale.

The API might look something like:
`setScaleType(ScaleType scaleType, boolean animate)`

**Comment by Jawnnypoo** [comment]
I think this goes beyond the scope of this library
