### ISSUE TITLE
Disable Arbitrary tininess (Nitpicky request)

### ISSUE THREAD

**Issue by sullyj3** [chrisbanes/PhotoView#212]
PhotoView allows zooming out til long after the image becomes invisible. If you pinch in, then release one finger, then use the same finger to continue pinching, you can continue zooming out for a long time. When you release, it can take quite a while for the image to zoom back in to its original size.

This doesn't seem like good behavior. An example of an app which doesn't do this is Google+. It only allows zooming out to a certain extent before it stops. I think this makes much more sense.

**Comment by Jawnnypoo** [comment]
This has been fixed
