### ISSUE TITLE
Set an initial Scale

### ISSUE THREAD

**Issue by kulio** [chrisbanes/PhotoView#213]
Hi,

I'm trying to set an initial Scale with PhotoView, but in all ways i tried i always have the same result: nothing.

I tried creating a Matrix with scale parameters and setting it with setDisplayMatrix(Matrix m), i tried all setScale PhotoAttacher methods and always the same...

Did someone try this and be success??

Thanks for reading ;)

**Comment by maniramezan** [comment]
+1

**Comment by wenmingvs** [comment]
try to use this

``` java

        photoView.setMaximumScale(10f);
        photoView.post(new Runnable() {
            @Override
            public void run() {
                photoView.setScale(10f,true);
            }
        });

```

**Comment by Jawnnypoo** [comment]
You just need to call photoView.setScale. As @wenmingvs mentioned, posting it in a runnable is a good idea if you are doing this before the view has been inflated and drawn
