### ISSUE TITLE
Personal advice :add  onAttachedToWindow method of PhotoView

### ISSUE THREAD

**Issue by hai046** [chrisbanes/PhotoView#225]
```
  @Override
    protected void onDetachedFromWindow() {
        mAttacher.cleanup();
        super.onDetachedFromWindow();
    }
```

when resume of the view is not on touch,
I feel we can do :   ` new PhotoViewAttacher(this)`  or resume `PhotoViewAttacher` in method of the  onAttachedToWindow()

**Comment by smarek** [comment]
This is acually good idea, I'll add it in **dev**, thank you
