### ISSUE TITLE
setScale() with animation doesn't work as expected

### ISSUE THREAD

**Issue by vmaubert** [chrisbanes/PhotoView#228]
Hi!

I have 2 buttons like this :

```java
button1.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {
         attacher.setScale(attacher.getMaximumScale(), 300, 150, true);
      }
});

button2.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {
         attacher.setScale(attacher.getMaximumScale(), 400, 250, true);
      }
});
```

Without animation it works perfectly.
But with animation if I clicked on the button1 (ok) and now on the button2, the camera doesn't move.

Thx!

**Comment by smarek** [comment]
I'm sorry, but that's not enough debug information to help you. Better to use stackoverflow.com or similar community next time, unless proven the library bug. Thank you
