### ISSUE TITLE
Question: Max image size?

### ISSUE THREAD

**Issue by Grunthos** [chrisbanes/PhotoView#230]
Just wondering how well the library supports large images. I am/was using another app based on ImageView and when passing a large image (12MP) to the viewer the logs show an OpenGL error on some phones.

Since this library is also based on ImageView, I was wondering if the same problem is likely?

(I had a quick scan though the code and could not see any code to manage loading smaller versions of an image)

**Comment by smarek** [comment]
Yes, the limitations are the same, we don't tile the bitmap in any way to prevent this.
