### ISSUE TITLE
Failure to find support dependencie

### ISSUE THREAD

**Issue by c0nscience** [chrisbanes/PhotoView#233]
Hi,

I'm pretty much new to android. I use this library in my project and while developing in intellij ultimate 14.0.2 everything works fine, but at the point of my maven ci build nothing works.

I got a maven build error:
```Failure to find com.android.support:support-v4:jar:19.+```

I inserted this to my maven pom:
```
<dependency>
    <groupId>com.github.chrisbanes.photoview</groupId>
    <artifactId>library</artifactId>
    <version>1.2.3</version>
    <type>jar</type>
</dependency>
```

Did you know how to use the lib with a maven build properly?

**Comment by smarek** [comment]
This dependency does not come from Maven Central, but from Android SDK itself, you have to have the Support Library v4 repository installed in SDK Manager, and then it should work.
