### ISSUE TITLE
issue to persist the zooming of image

### ISSUE THREAD

**Issue by dhrumit123** [chrisbanes/PhotoView#235]
Hi, I am using photoview inside viewpager. I am setting normal size image on imageview inside viewpager . And when user pinch to zoom i need to get large image for the same and display it in imageview with same zoom level . But when large image comes and apply to imageview the zoom level resets . Please help on this as sson as possible.

**Comment by koso** [comment]
I'd like to see this feature as well

**Comment by pavei** [comment]
@dhrumit123 did you solved?

**Comment by dhrumit123** [comment]
@pavei  sorry not solved yet..

**Comment by Catherine0728** [comment]
I don't quite understand what you mean? You mean when the user to zoom in, and then again when the biggest, we reduce the proportion of a zoom when need to reset the proportion? Right?

**Comment by Catherine0728** [comment]
@dhrumit123

**Comment by pavei** [comment]
If you create an ImageView then load a bitmap make zoom and put another bitmap it will reset

**Comment by Jawnnypoo** [comment]
This would be the responsibility of the individual implementations to keep up with zoom level, and not the responsibility of the library.

**Comment by Queatz** [comment]
Has anyone solved this? Running into the same issue
