### ISSUE TITLE
LoggerManager not always being used

### ISSUE THREAD

**Issue by schwiz** [chrisbanes/PhotoView#238]
Sometimes you just jump straight to the android logs.  For example in PhotoviewAttacher line 297

Log.i(LOG_TAG,
                    "ImageView no longer exists. You should not use this PhotoViewAttacher any more.");

**Comment by smarek** [comment]
Thank you for report, it's fixed in 2826f89540a9e8364053e96a210414cd7a3183de

**Comment by schwiz** [comment]
Thanks for the update. Will milestone 1.2.4 be released to maven soon?

**Comment by smarek** [comment]
Yes, Chris should take care of the release in matter of days.
Also I've just left the library as maintainer, so it's officially unsupported, unless someone takes my place
