### ISSUE TITLE
I want to make "GO TO CENTER OF IMAGE" button when zoom-in.

### ISSUE THREAD

**Issue by abcd476555** [chrisbanes/PhotoView#241]
When zoom-in, the image of photoview will larger than mobile screen.
So, I want to make button that move mobile screen to center of the image, and the image still zoomed.
I have no idea which variable I have to set in OnClickListener.

Could someone guide me please.
just move mobile screen to specific position such as (100, 200) etc.

**Comment by smarek** [comment]
This is out-of-scope of this issue tracker
