### ISSUE TITLE
Get Wrong Animation effect when use ActivityOptions.makeSceneTransitionAnimation

### ISSUE THREAD

**Issue by bearprada** [chrisbanes/PhotoView#243]
it's a new transition animation in Android 5.0. but `PhotoView` will get wrong size when play animation like 
![hhlyt](https://cloud.githubusercontent.com/assets/1080103/6141860/bb14e530-b1e6-11e4-8a21-802256f9d65b.gif)

**Comment by nicomott** [comment]
Would love to see this fixed too. It makes Lollipop transition unusable. 
I tried to postpone the transition by calling `startPostponedEnterTransition` in `OnPreDrawListener` but it doesn't change a thing. 
I tried to extend `ChangeImageTransform` to add logs and compare these values with the ones that I get when using a simple `ImageView` instead of a `PhotoView`, but everything seems to be the same. Does anyone have an idea?

**Comment by deviant-studio** [comment]
Same problem.
The only way i workarounded it: wrap imageviews into PhotoViewAttachers on enter animation finish. And clean PhotoViewAttachers on destroy views or activity exit

**Comment by T-Rex96** [comment]
Can you share the code to do this? I'm struggling with this problem too, but don't want to move away from PhotoView

**Comment by deviant-studio** [comment]
https://github.com/deviant-studio/VKontakte-Plus/blob/master/app/src/main/java/ds/vkplus/ui/activity/PhotosActivity.kt
it's on kotlin though

**Comment by T-Rex96** [comment]
Doesn't really help me. but thanks - Hope this gets fixed soon or a workaround is found

**Comment by nbarraille** [comment]
Same here.
I currently work around this by having 2 ImageViews in the 2nd activity, a standard `ImageView` for the transition, and a `PhotoView` that gets displayed when the transition is over on top of it

**Comment by miav** [comment]
Is there any news on this?

**Comment by andrey-blak** [comment]
I had similar animation issue. Magic call `photoViewAttacher.update()` helped in my case. 
```
public class DetailsTransition extends ChangeImageTransform {
    @Override
    public void captureStartValues(TransitionValues transitionValues) {
        updateAttacher(transitionValues);
        super.captureStartValues(transitionValues);
    }

    @Override
    public void captureEndValues(TransitionValues transitionValues) {
        updateAttacher(transitionValues);
        super.captureEndValues(transitionValues);
    }

    private static void updateAttacher(TransitionValues transitionValues) {
        View view = transitionValues.view;
        if (view instanceof PhotoView) {
            PhotoView imageView = (PhotoView) view;
            PhotoViewAttacher photoViewAttacher = (PhotoViewAttacher) imageView.getIPhotoViewImplementation();
            photoViewAttacher.update();
        }
    }
}
```

**Comment by Solban** [comment]
Why not use imageview and PhotoVIewAttacher, something like this:
 public void onTransitionEnd(Transition transition) { 
                    PhotoViewAttacher attacher = new PhotoViewAttacher();
}
It seems to have fixed the issue.

**Comment by Jawnnypoo** [comment]
This should be resolved in 1.3.0 thanks to @Rexee

**Comment by bearprada** [comment]
thanks @Rexee 👍

**Comment by prcGit** [comment]
Shared transitions not working.... 
Version 1.3.1, Replacing the photoView by an imageView it works perfectly...

**Comment by ucmobdev** [comment]
Seems like this issue reemerged in 2.1.3 
Downgrading to 2.0.0 helped

**Comment by T-Rex96** [comment]
Everything works fine for me on 2.2.0
