### ISSUE TITLE
Unexpected exception while pinch to zoom

### ISSUE THREAD

**Issue by tsulok** [chrisbanes/PhotoView#244]
After two fingered pinch to zoom (scale 1.5), followed by a zoom out (scale about 0.75) without releasing the view on various devices (eg Samsung Mini 3), the following exception happens:
E/webcoreglue﹕ Should not happen: no rect-based-test nodes found

**Comment by smarek** [comment]
Can you please give out full stacktrace? This looks like problem of specific device / firmware.
Are you talking about Samsung official OTA ROMs only?

**Comment by Jawnnypoo** [comment]
I am fairly certain this is an incorrect stack trace if there was an issue with zooming. See the readme if the problem occurs when the PhotoView is placed within a ViewGroup
