### ISSUE TITLE
OutOfMemoryError when I use big image in ViewPager

### ISSUE THREAD

**Issue by 4332weizi** [chrisbanes/PhotoView#246]
When I use PhotoView to display image bigger (such as image width : 1920px ,height : 1080px) in ViewPager, it caused OutOfMemoryError exception.
but if I use Universal Image Loader ,the image can't to see clearly after zoom in.

**Comment by qq2653203** [comment]
when i use viewpager MAT shows this
![issue](https://cloud.githubusercontent.com/assets/8454148/7015739/498d1306-dd0b-11e4-88fb-b90b0adfc505.png)

**Comment by smarek** [comment]
Looks like you've attached PhotoView library multiple times, can you verify this please? 
Also there was bug #250 where multiple instances of attacher were in place, you can test with latest **dev** contents if it gets any better

**Comment by manhphi65** [comment]
I have same problem.
I solve my problem when use :
 + FragmentStageAdapterPager for ViewPager.

**Comment by Jawnnypoo** [comment]
@manhphi65 that does not solve the problem, more like a bandage for a different problem. There is not enough info here to go off of. I am guessing that ViewPager had 8 pages in it and therefore 8 Attachers. I do not think there is any other way it could be duplicated
