### ISSUE TITLE
PhotoViewAttacher created twice for each PhotoView

### ISSUE THREAD

**Issue by Takaitra** [chrisbanes/PhotoView#250]
Two PhotoViewAttachers are instantiated for each PhotoView, the second one replacing the first. This is because PhotoView#init() is called from two places.

1) The PhotoView constructor
2) PhotoView#onAttachedToWindow

This can cause problems when, for example, a OnViewTapListener is set after the PhotoView is constructed. When the view is then attached, a new PhotoViewAttacher is created and the tap listener is lost.

**Comment by smarek** [comment]
Thanks for report, I've fixed that just now
