### ISSUE TITLE
Gradle Issues

### ISSUE THREAD

**Issue by toast7195** [chrisbanes/PhotoView#257]
When I apply this library to my android studio and try to sync, I get this message : 

Error:No such property: GROUP for class: org.gradle.api.publication.maven.internal.ant.DefaultGroovyMavenDeployer

How can I solve it?

**Comment by kenMarquez** [comment]
I have the same problem  , can you resolved it?

**Comment by smarek** [comment]
This one comes from our maven release gradle plugin
see the answer here: 
https://stackoverflow.com/questions/28450549/errorno-such-property-group-for-class-org-gradle-api-publication-maven-intern

The line you can comment out is in this build.gradle file:
https://github.com/chrisbanes/PhotoView/blob/master/library/build.gradle

**Comment by toast7195** [comment]
thank you!
