### ISSUE TITLE
[Question] How to add PhotoView library v 1.2.4 as compile '' in build.gradle? 

### ISSUE THREAD

**Issue by kraizman** [chrisbanes/PhotoView#260]
HI, change log (https://github.com/chrisbanes/PhotoView/wiki/Changelog) says that you have already version 1.2.4 but i can only find version 1.2.3 and master contains 1.2.3. How can i import without checkout of project and switch to dev branch?

**Comment by smarek** [comment]
@chrisbanes is currently taking care of this, release should be available as soon as possible.

**Comment by schwiz** [comment]
@chrisbanes can you please release this?

**Comment by androidsihai1** [comment]
I have reslove this question ,

**Comment by schwiz** [comment]
Curious what the holdup for this release is. Is there an issue with the 1.2.4 build?

**Comment by vernazza** [comment]
You have to add mavenCentral as repository.

In your gradle file you'll have

buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
...

**Comment by Jawnnypoo** [comment]
It should be available now. Check the README and you can see the dependency group has changed. 1.2.4 should be available.
