### ISSUE TITLE
Some images appear small during a scroll

### ISSUE THREAD

**Issue by wzrd-clss** [chrisbanes/PhotoView#261]
sometimes when I am scrolling through images on my listview, an image will appear small. The image that appears to have shrank only returns to its normal size when it is scrolled to the top of the screen. these are images that were lazy loaded from the internet. what could be causing this on photoview 1.2.3?
a gist of the list adapter
https://gist.github.com/wiel/ed92d41ed8151b0a4959

**Comment by caixuejian** [comment]
me too

**Comment by Jawnnypoo** [comment]
I believe this does not have to do with this library but instead something to do with the image loading process. It is hard to tell since the sample has been removed
