### ISSUE TITLE
The image failed to scale after rotated.

### ISSUE THREAD

**Issue by JuanbingTeam** [chrisbanes/PhotoView#265]
Hi guys,
I use PhotoView as the control to display my images. The images were captured by Samsung Note 3, so it's marked as rotated in its EXIF info (Orientation 90 degree). I don't want to rotate it back by using bitmap, so i rotate and scale the whole image_view(Photo view) instead. After i rotated the control , everything looks well except it can't be dragged in x side.  

            float[] scaleRate = getScaleRate();
            ViewHelper.setRotation(this.mainImage, degree);
            ViewHelper.setScaleX(this.mainImage, scaleRate[0]);
            ViewHelper.setScaleY(this.mainImage, scaleRate[1]);

SO, WHAT could / should i do to make sure the image can be dragged in x side?

Thanks, in advance.

here is the origin image:
![26e3a17f921a7466d9778ab1b9632b49](https://cloud.githubusercontent.com/assets/11962337/7251694/50b27c60-e860-11e4-9322-a6cecc51d4b9.png)

**Comment by Jawnnypoo** [comment]
Instead of rotating the view, you should use an image loading library that respects EXIF info
