### ISSUE TITLE
[Question] How can I disable zoom out feature with PhotoView?

### ISSUE THREAD

**Issue by ArthurWangNet** [chrisbanes/PhotoView#266]
Hi:

It seems the zoom out feature on Galaxy S5 will cause exception ArrayIndexOutOfBoundsException. I can't track down where goes wrong in the code but I do hope if I could simply turn off the zoom out but only keeps the zoom in function. Could you kindly let me know how could I achieve that? Thank you!

**Comment by Jawnnypoo** [comment]
See the README as to why you are getting this exception, whichever ViewGroup your PhotoView is in, you will need to extend it to apply the fix
