### ISSUE TITLE
Does it work with image loading libraries like Picasso and Glide?

### ISSUE THREAD

**Issue by gauravsoti1** [chrisbanes/PhotoView#274]
I want images being loaded from server using Picasso to have pinch, zoom functionality. Has anyone used this library with Picasso? Could you please provide the code where you use Picasso with this library?

**Comment by 20015jjw** [comment]
I have used it with Ion. You simple use `PhotoViewAttacher` on the `ImageView`.

**Comment by Jawnnypoo** [comment]
Yes, just take a look at the [sample app](https://github.com/chrisbanes/PhotoView/tree/master/sample)
