### ISSUE TITLE
could add the user taps  on the out of actual photo

### ISSUE THREAD

**Issue by natman44** [chrisbanes/PhotoView#275]
Add click on the picture outside the scope of the callback, so that you can click on the picture of the area, shut it down

**Comment by Jawnnypoo** [comment]
Can you explain this further? I am not sure what you mean.

**Comment by celerysoft** [comment]
do u mean add a listener to listen tap out of the photo? like a dialog if u click outside the dialog the dialog will dismiss.

u can use both `setOnViewTapListener` and `setOnPhotoTapListener`. when u tap the photo it will callback the OnPhotoTapListener. u tap outside the photo it will  call back the OnViewTapListener.

**Comment by natman44** [comment]
ththanks

**Comment by Jawnnypoo** [comment]
This has since been added to the library. Just add an OnPhotoTapListener. See the sample for more
