### ISSUE TITLE
Can the height/width of the initial image view be set?

### ISSUE THREAD

**Issue by jwood803** [chrisbanes/PhotoView#278]
This implementation is great, but I was just wondering if there was a way to set the initial height and width of the image as it gets loaded before I start zooming or panning?

**Comment by ConorGarry** [comment]
Came here to ask the same thing. Had you any luck this this since, @jwood803?

**Comment by jwood803** [comment]
Unfortunately not @ConorGarry :{

I even had this [StackOverflow question](http://stackoverflow.com/questions/32925854/can-the-initial-image-be-adjusted-in-the-xamarin-photoview-component) but not much response.

I did try to create a sample project to show what was going on, but kind of just gave up on it. I may return to it this weekend or so and share what all I got with you.

**Comment by Jawnnypoo** [comment]
you just need to provide a custom scale type to change which region of the image shows initially
