### ISSUE TITLE
load drawable oom

### ISSUE THREAD

**Issue by JWBlueLiu** [chrisbanes/PhotoView#281]
http://blog.sina.com.cn/s/blog_710225790101e1n8.html
dowload pic from this website

**Comment by Jawnnypoo** [comment]
Can't really help you there. You still get out of memory errors if you use an ImageView, no?

**Comment by JWBlueLiu** [comment]
If i use ImageView will oom.But i think PhotoView should not oom.Do i need to decode by myself?

**Comment by JWBlueLiu** [comment]
PhotoView can't avoid oom?

**Comment by Jawnnypoo** [comment]
If a bitmap is massive, any view will have an out of memory error, reguardless of what it is. You can try a different image loading library such as Glide and see if you get better results
