### ISSUE TITLE
OutOfMemoryError when using ImageView.setContentUri() with large files

### ISSUE THREAD

**Issue by makisce** [chrisbanes/PhotoView#283]
When I try to create the PhotoView object using image captured from camera (large image >2MB) it throws an OutOfMemoryError exception.

The sample code I am using to test the library is:

            mPhotoView = new PhotoView(this);
            mRlImageContainer.addView(mPhotoView);
            mPhotoView.setScaleType(ImageView.ScaleType.CENTER_CROP);
            mPhotoView.setImageURI(Uri.fromFile(imageFile));

Am I doing something wrong here?

**Comment by Jawnnypoo** [comment]
Does this occur if you do this on a normal ImageView?

**Comment by makisce** [comment]
Yes, it does when I put the full resolution image. The problem is that the library should do some kind of subsampling in order to use less memory. To use this library for low resolution images is not quite logical, zooming is required when you work with large files.

**Comment by Jawnnypoo** [comment]
That is beyond the scope of the library, at least for now.

**Comment by k3b** [comment]
Android has a limit that it cannot display images larger than 4096*4096. if the image is bigger in one dimension it throws OutOfMemoryError. #373 should fix this.
