### ISSUE TITLE
compile 'com.commit451:PhotoView:1.2.4' not working

### ISSUE THREAD

**Issue by AnthonyKoueik** [chrisbanes/PhotoView#286]
i can't see your lib classes  with this gradle in my code .

**Comment by Jawnnypoo** [comment]
Are you saying it won't resolve at all or just you cannot see the source?

**Comment by AnthonyKoueik** [comment]
When i try to call your classes after syncing gradle  compile 'com.commit451:PhotoView:1.2.4' 
i can't see any.
I used this one instead compile 'com.github.chrisbanes.photoview:library:1.2.2' and it worked fine

**Comment by guillermomuntaner** [comment]
+1 Gradle build does not complain about not being able to find the library, but PhotoView classes are not accesible after compile.

**Comment by mturki** [comment]
I use this :
    compile 'com.github.chrisbanes.photoview:library:1.2.4'
And it works properly for me. But perhaps this is not the right way to do.

**Comment by Jawnnypoo** [comment]
It is possible that you are include mavenCentral and not jcenter. This dependency now requires you to use jcenter

**Comment by alvinmeimoun** [comment]
I added the line maven { url "https://jitpack.io" } to the root build.gradle file but doesn't work for me Error:Could not find com.github.chrisbanes:PhotoView:1.3.0.

**Comment by OnlyMyRailgun** [comment]
```
allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```
worked for me!

**Comment by pavel-ismailov** [comment]
right link is

```
implementation 'com.github.chrisbanes.photoview:library:1.2.4'
```

Author should change link in README

**Comment by idedalusse** [comment]
Thikn's :pavel-ismailov

**Comment by Sulorb** [comment]
> ```
> implementation 'com.github.chrisbanes.photoview:library:1.2.4'
> ```

Looks like the good answer but I don't know in what file I'm supposed to change it, could you be more specify?

**Comment by sashakalapusha** [comment]
> > ```
> > implementation 'com.github.chrisbanes.photoview:library:1.2.4'
> > ```
> 
> Looks like the good answer but I don't know in what file I'm supposed to change it, could you be more specify?


Here `../node_modules/com-sarriaroman-photoviewer/src/android/photoviewer.gradle`
Replace all the 'compile' with 'implementation'

**Comment by ddesignercoder** [comment]
@sashakalapusha: I tried but still same error.

**Comment by sashakalapusha** [comment]
@ddesignercoder I've replaced all the 'compile' with 'implementation' and re-open Android Studio.

Now photoviewer.gradle looks:
`repositories{
  jcenter()
}

dependencies {
   implementation 'com.commit451:PhotoView:1.2.4'
   implementation 'com.squareup.picasso:picasso:2.71828'
}

android {

}`

**Comment by RenzoPH** [comment]
Hi all, I encountered this issue also. May I know if these works after you add in the specific .gradle file in your android folder?

I would like to ask.. where's did you input these implementation in your gradle file

> Configure project :app
WARNING: DSL element 'dexOptions' is obsolete.
It will be removed in version 8.0 of the Android Gradle plugin.

FAILURE: Build failed with an exception.

* Where:
Script '/Users/runner/work/1/s/node_modules/com-sarriaroman-photoviewer/src/android/photoviewer.gradle' line: 6

* What went wrong:
A problem occurred evaluating script.
> Could not find method compile() for arguments [com.commit451:PhotoView:1.2.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by jaygs97** [comment]
> > > ```
> > > implementation 'com.github.chrisbanes.photoview:library:1.2.4'
> > > ```
> > 
> > 
> > Looks like the good answer but I don't know in what file I'm supposed to change it, could you be more specify?
> 
> Here `../node_modules/com-sarriaroman-photoviewer/src/android/photoviewer.gradle` Replace all the 'compile' with 'implementation'

I tried this, but it still threw the same err. Hence, I updated the code in

**Comment by jaygs97** [comment]
I tried this, but it still threw the same err. Hence, I updated the code at,
'platforms\android\com-sarriaroman-photoviewer\<app-name>-photoviewer.gradle'

This worked for me. The above path was available after build ('ionic cordova platform add android').

**Comment by jaygs97** [comment]
I tried this, but it still threw the same err. Hence, I updated the code at,
`platforms\android\com-sarriaroman-photoviewer<app-name>-photoviewer.gradle`

This worked for me. The above path was available after add android command (`ionic cordova platform add android`).

**Comment by tortuch611** [comment]
I'm getting this issue yet in ionic-cordova latest version.
