### ISSUE TITLE
Minimum scale to zoom out

### ISSUE THREAD

**Issue by amitclickapps** [chrisbanes/PhotoView#287]
How can i set to minimum scale so that image can't be zoom out from that point. 
currently i use attcaher.setMinimumscale(20f) but it gives exception.

**Comment by CoderYuan** [comment]
+1
I'm looking at onScale(float, float, float) of PhotoViewAttacher.java
I added the condition check
if ((getScale() < mMaxScale || scaleFactor < 1f)
                `&& (getScale() > mMinScale || scaleFactor > 1f)`) {

No sure if it's the correct way.

**Comment by sergio-moura88** [comment]
+1
This would be very helpful. @CoderYuan that approach helped me! Thanks.

**Comment by Jawnnypoo** [comment]
You are setting the minimum scale to something higher than the maximum. Make sure you are setting the values to not be greater than the other ones
