### ISSUE TITLE
Can't compile. Error!

### ISSUE THREAD

**Issue by borjaruiz** [chrisbanes/PhotoView#292]
I get this error when I run my app, after adding the "compile" sentence.

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by Jawnnypoo** [comment]
Not related to this project.
