### ISSUE TITLE
Provide getters for all the listeners

### ISSUE THREAD

**Issue by jameydeorio** [chrisbanes/PhotoView#295]
Like `getOnPhotoTapListener()` and `getOnViewTapListener()`, I would like to have getters for scale change, matrix change, long click, and double tap listeners. This is primarily for tests, to trigger these actions.

Is there a reason why we only have the two mentioned above?

**Comment by Jawnnypoo** [comment]
No reason other than it hasn't been developed! If you want it, make a pull request against develop and I would be happy to review it

**Comment by Jawnnypoo** [comment]
There is actually no reason to have getters on the listeners. This is never really a provided method in Android, as you can just keep references to your listeners yourself
