### ISSUE TITLE
how can I double-tap to enlarge then double-tap back

### ISSUE THREAD

**Issue by a1018875550** [chrisbanes/PhotoView#298]
how can I double-tap to enlarge then double-tap reduction not enlarge again

**Comment by Jawnnypoo** [comment]
If that is your desired behaviour, you are better off using a custom implementation, or forking this library and doing it yourself

**Comment by alistefano** [comment]
It would be very useful to have a public API that turns off the medium scale.

**Comment by cklar** [comment]
I would also like to see that as a feature of the public API

**Comment by Bruno-Casado** [comment]
> I would also like to see that as a feature of the public API
> 
> But for now overriding the DefaultOnDoubleTapListener also works
> 
> ```java
>    @Override
>     public boolean onDoubleTap(MotionEvent ev) {
>         if (photoViewAttacher == null)
>             return false;
>         try {
>             float scale = photoViewAttacher.getScale();
>             float x = ev.getX();
>             float y = ev.getY();
> 
>             if (scale < photoViewAttacher.getMaximumScale()) {
>                 photoViewAttacher.setScale(photoViewAttacher.getMaximumScale(), x, y, true);
>             } else {
>                 photoViewAttacher.setScale(photoViewAttacher.getMinimumScale(), x, y, true);
>             }
>         } catch (ArrayIndexOutOfBoundsException e) {
>             // Can sometimes happen when getX() and getY() is called
>             Timber.e(e, "Error during double tab");
>         }
> 
>         return true;
>     }
> ```

How can I override this method localy?

**Comment by Frank1234** [comment]
> > I would also like to see that as a feature of the public API
> > But for now overriding the DefaultOnDoubleTapListener also works
> > ```java
> >    @Override
> >     public boolean onDoubleTap(MotionEvent ev) {
> >         if (photoViewAttacher == null)
> >             return false;
> >         try {
> >             float scale = photoViewAttacher.getScale();
> >             float x = ev.getX();
> >             float y = ev.getY();
> > 
> >             if (scale < photoViewAttacher.getMaximumScale()) {
> >                 photoViewAttacher.setScale(photoViewAttacher.getMaximumScale(), x, y, true);
> >             } else {
> >                 photoViewAttacher.setScale(photoViewAttacher.getMinimumScale(), x, y, true);
> >             }
> >         } catch (ArrayIndexOutOfBoundsException e) {
> >             // Can sometimes happen when getX() and getY() is called
> >             Timber.e(e, "Error during double tab");
> >         }
> > 
> >         return true;
> >     }
> > ```
> 
> How can I override this method localy?

mPhotoView.setOnDoubleTapListener(new GestureDetector.OnDoubleTapListener() {
            @Override ...
