### ISSUE TITLE
Error: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1

### ISSUE THREAD

**Issue by leveychen** [chrisbanes/PhotoView#303]
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
How can I do?

**Comment by McSullivan** [comment]
Having the same issue and can't figure out how to solve this. Any ideas?

**Comment by Jawnnypoo** [comment]
Take a look at the README, the solution is there. Override the ViewGroup the PhotoView is in with the solution provided in the README.
