### ISSUE TITLE
Cannot add PhotoView as a library in Android Studio 

### ISSUE THREAD

**Issue by truongluong1314** [chrisbanes/PhotoView#305]
I create a new project and right click on File -> New -> Import module -> Choose PhotoView as my library (only the library folder).

When I click on Finish button, there is an error that it cannot find "com.novoda.bintray-release".

If i miss any step, please let me know. I really want to say thank you for the great library and love to use this library.

**Comment by Jawnnypoo** [comment]
check out the build.gradle file of the repository. You will need to add the imports there for bintray release.
