### ISSUE TITLE
Can not restore the original image size when i use the PhotoView in the ViewPager?

### ISSUE THREAD

**Issue by Zihuatanejo50** [chrisbanes/PhotoView#310]
Firstly,I use the PhotoView in the ViewPager.When i zoom out/in the current image,and then slide to the next image,and slide back the previous image.Why can't restore to the original image size?Unexpectedly,i get the zoom out/in image.How  can i  resolve this problem?Thanks!

**Comment by shanyezhihe** [comment]
I have the save requirement now and I try to use the getdisplayMatrix()  to save the state for last photoview and setDisplayMatrix() when I slide back ,but the setDisplayMatrix() has changed the state of last photoview when I slide back.I think you can give it a try.

**Comment by Jawnnypoo** [comment]
You will basically just have to add an OnPageChangeListener to the view pager, and reset the zoom level when the page changes

**Comment by ericn37** [comment]
Hi @Jawnnypoo how do I reset the zoom level?

**Comment by piotrros** [comment]
Try this:

```
    public void reset(){
        imvPhoto.setDisplayMatrix(new Matrix());
        imvPhoto.setSuppMatrix(new Matrix());
    }
```
