### ISSUE TITLE
 Plugin with id 'com.novoda.bintray-release' not found. when I add the library this is a error  

### ISSUE THREAD

**Issue by poecook** [chrisbanes/PhotoView#311]
when I add the library this is a error :Plugin with id 'com.novoda.bintray-release' not found.

**Comment by Jawnnypoo** [comment]
So you are adding just the library module? You will have to add the gradle include as you see it in the outermost build.gradle file. Alternatively, you can use gradle to import the dependency from jcenter

**Comment by raghu-innominds** [comment]
Just add this line 
classpath 'com.novoda:bintray-release:0.7.0'
It worked for me

**Comment by SheharyarEjaz** [comment]
Just add it in built.gradle (Project level)  
classpath 'com.novoda:bintray-release:0.8.0'

under 

 dependencies {
        classpath 'com.android.tools.build:gradle:3.1.3'
        classpath 'com.google.gms:google-services:4.0.1'
        classpath 'com.novoda:bintray-release:0.8.0'
    }
Note:
       make sure you are adding this dependency at Project level gradle
