### ISSUE TITLE
PhotoView is not accepting urls that work with Fresco, Picasso and Glide

### ISSUE THREAD

**Issue by julianonunes** [chrisbanes/PhotoView#316]
I'm using the following code to load my images:

photoView.setImageURI(pageList.get(position));

The get method returns an object of android.net.Uri that is generated by using Uri.parse(). This same object has been tested when using other libraries (only replacing spaces by %20), however PhotoView is causing an exception:

E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: /http:/hqcomicsonline.com.br/leitor/hq/Doctor Who - O Oitavo Doutor/02/00b cópia cópia.jpg: open failed: ENOENT (No such file or directory)

Isn't it compatible with accents?

**Comment by Jawnnypoo** [comment]
I think you are confused. First of all, PhotoView does not do anything special with ImageView.setImageURI(). It simply listens for this event to happen. If you are using Picasso, Glide, Fresco, or any other image loading library, they should be doing the image loading completely, and you should not need to call `setImageURI` at all. See the sample app
