### ISSUE TITLE
Stopped with Android 6.

### ISSUE THREAD

**Issue by juanlabrador** [chrisbanes/PhotoView#317]
With Android 6, load without problem, but I can't do zoom, nothing, and the app stopped. Thanks.

**Comment by Jawnnypoo** [comment]
Can you give more specifics, like what device you are using, what the crash actually is? I cannot do very much with such limited information.

**Comment by juanlabrador** [comment]
Right. Sorry for the limited comment. When open, load image fine, but the screen freeze, later many seconds, this works, if before you touch the image, show message of "app stopped". 

This is the message log.
01-28 15:58:36.605 1871-1885/? E/ActivityManager: ANR in com.farmappweb.pests.androidpests (com.farmappweb.pests.androidpests/.activities.ShowImageActivity)
                                                  PID: 15843
                                                  Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 43.  Wait queue head age: 5606.7ms.)
                                                  Load: 14.11 / 13.37 / 13.34
                                                  CPU usage from 0ms to 5635ms later:
                                                    100% 15843/com.farmappweb.pests.androidpests: 96% user + 3.1% kernel / faults: 12224 minor 32 major
                                                    40% 1871/system_server: 18% user + 21% kernel / faults: 4587 minor 95 major
                                                    0.1% 479/debuggerd: 0% user + 0.1% kernel / faults: 8967 minor 35 major
                                                    11% 2881/com.android.systemui: 7.9% user + 3.3% kernel / faults: 2231 minor 11 major
                                                    11% 3516/com.motorola.audiomonitor: 5.5% user + 5.8% kernel / faults: 2692 minor 30 major
                                                    9% 3562/com.android.phone: 3.5% user + 5.5% kernel / faults: 2434 minor 10 major
                                                    4.6% 3488/com.motorola.process.system: 4% user + 0.5% kernel / faults: 1859 minor 10 major
                                                    4.6% 3555/com.motorola.modemservice: 1.5% user + 3% kernel / faults: 1865 minor 2 major
                                                    3.5% 3509/com.android.nfc: 2.3% user + 1.2% kernel / faults: 1708 minor 8 major
                                                    0.1% 2891/com.motorola.process.slpc: 0% user + 0% kernel / faults: 1999 minor 1 major
                                                    2.1% 357/surfaceflinger: 0.7% user + 1.4% kernel / faults: 6 minor
                                                    1.5% 178/mmcqd/0: 0% user + 1.5% kernel
                                                    0% 3499/com.qualcomm.services.location: 0% user + 0% kernel / faults: 1291 minor 2 major
                                                    0.5% 14669/kworker/0:0: 0% user + 0.5% kernel
                                                    0.5% 15928/com.instagram.android: 0.3% user + 0.1% kernel / faults: 447 minor
                                                    0.3% 93/kswapd0: 0% user + 0.3% kernel
                                                    0.3% 7738/ksoftirqd/1: 0% user + 0.3% kernel
                                                    0.3% 7742/ksoftirqd/2: 0% user + 0.3% kernel
                                                    0.3% 7746/ksoftirqd/3: 0% user + 0.3% kernel
                                                    0.1% 3/ksoftirqd/0: 0% user + 0.1% kernel
                                                    0.1% 7/kworker/u:0H: 0% user + 0.1% kernel
                                                    0.1% 162/cfinteractive: 0% user + 0.1% kernel
                                                    0.1% 227/logd: 0.1% user + 0% kernel
                                                    0.1% 480/rild: 0.1% user + 0% kernel / faults: 4 minor
                                                    0.1% 3825/irq/33-cpubw_hw: 0% user + 0.1% kernel
                                                    0.1% 7737/kworker/1:1H: 0% user + 0.1% kernel
                                                    0.1% 7741/kworker/2:2H: 0% user + 0.1% kernel
                                                    0.1% 7990/kworker/3:2: 0% user + 0.1% kernel
                                                    0.1% 8104/com.google.android.gms.persistent: 0% user + 0.1% kernel / faults: 1 minor
                                                    0.1% 12706/adbd: 0% user + 0.1% kernel
                                                    0.1% 13077/kworker/u:6: 0% user + 0.1% kernel
                                                    0.1% 15655/kworker/u:3: 0% user + 0.1% kernel
                                                    0.1% 19392/MC_Thread: 0% user + 0.1% kernel
                                                   +0% 16253/kworker/3:1: 0% user + 0% kernel
                                                  55% TOTAL: 36% user + 15% kernel + 2.7% iowait + 0% softirq
                                                  CPU usage from 5065ms to 5590ms later:
                                                    112% 15843/com.farmappweb.pests.androidpests: 110% user + 1.8% kernel / faults: 683 minor
                                                      97% 15843/ts.androidpests: 97% user + 0% kernel
                                                      14% 15853/HeapTaskDaemon: 12% user + 1.8% kernel
                                                    5.6% 1871/system_server: 0% user + 5.6% kernel / faults: 1 minor
                                                      5.6% 1885/ActivityManager: 0% user + 5.6% kernel
                                                      1.8% 2671/WifiStateMachin: 1.8% user + 0% kernel
                                                    2.8% 3516/com.motorola.audiomonitor: 2.8% user + 0% kernel
                                                      1.4% 3516/la.audiomonitor: 1.4% user + 0% kernel
                                                    1.3% 357/surfaceflinger: 0% user + 1.3% kernel
                                                      1.3% 522/DispSync: 0% user + 1.3% kernel
                                                      1.3% 997/EventThread: 0% user + 1.3% kernel
                                                    1.4% 3825/irq/33-cpubw_hw: 0% user + 1.4% kernel
                                                  30% TOTAL: 29% user + 0.9% kernel


The phone is un Moto X (2G) Android 6.0

**Comment by RoundSparrow** [comment]
Have you tried the "PhotoView Sample" app on Google Play?

**Comment by Jawnnypoo** [comment]
@juanlabrador can you confirm that this occurs in the current sample app?

**Comment by Jawnnypoo** [comment]
I dont think this is actually an issue with this library
