### ISSUE TITLE
the imgview is not int the center, when i use the PhotoViewAttacher

### ISSUE THREAD

**Issue by AnswerZhao** [chrisbanes/PhotoView#320]
the imgview is not int the center, when i use the PhotoViewAttacher. The photo is always at the top ,but when i touch the photo , the photo move to the center.Please help me .

**Comment by devapalanisamy** [comment]
Yes. I have same issue 😟

**Comment by devapalanisamy** [comment]
![img_6436](https://cloud.githubusercontent.com/assets/5352735/12784518/86fea256-ca7f-11e5-8d92-ecb32653ba80.jpg)
![img_6437](https://cloud.githubusercontent.com/assets/5352735/12784517/86fd59dc-ca7f-11e5-9f9d-bdeb7f761768.jpg)

**Comment by Jawnnypoo** [comment]
Pasting some XML in here to show how the layout looks would be helpful

**Comment by devapalanisamy** [comment]
@Jawnnypoo  I am creating ImageView Programmatically and adding it to layout.

**Comment by Jawnnypoo** [comment]
Can you paste the code you are using to programatically add the view then?

**Comment by devapalanisamy** [comment]
Setting zoomable to false resolved my issue.

**Comment by AnswerZhao** [comment]
I have resolve it. in the viewpager, when you show image using the PhotoViewAttacher,  the image always don't show in the center, i don't know why. However,i found the right way is to use the PhotoView in the adapter of viewpager.

**Comment by tibbi** [comment]
It was broken the same way for me too, while adding the PhotoViewAttacher in InstantiateItem at my PagerAdapter. However using the PhotoView instead of ImageView as written at the sample fixed it. It was broken the same way on android 4.3 and 5.1.1. If the image was too high, it was alligned Left instead of Top. Here is a commit from going the broken to the working version in case you need it. https://github.com/SimpleMobileTools/Simple-Gallery/commit/3983428d5fd4810e28fadd915a59ca08558ba4ae

**Comment by getsmp** [comment]
@tibbi have been experiencing this too, solved with help of you. Thanks for sharing the code!

**Comment by ihainan** [comment]
Same issue on latest version (1.2.5) and use PhotoView instead of ImageView resolve it.

**Comment by E2Clince** [comment]
When I set zoomable to false image view is showed OK. Also when I use PhotoView. But those solutions are not valid for me because I NEED zoom and a center image.

**Comment by yurimmm** [comment]
@E2Clince  I finally found a solution!! Refer to this website! 
http://stackoverflow.com/questions/33479400/android-photoview-setdisplaymatrix

**Comment by fantasymaker-cn** [comment]
@tibbi 's way works for me. Use PhotoView instead of ImageView. Thanks!!

**Comment by yeonkyuJeong** [comment]
I solved this issue. using the next way.
mAttacher.setOnScaleChangeListener(new PhotoViewAttacher.OnScaleChangeListener() {
                @Override
                public void onScaleChange(float scaleFactor, float focusX, float focusY) {
                    RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.MATCH_PARENT, RelativeLayout.LayoutParams.MATCH_PARENT);
                    params.addRule(RelativeLayout.CENTER_IN_PARENT);
                    mAttacher.getImageView().setLayoutParams(params);
                }
            });

**Comment by fuzyfuzi17** [comment]
you guyz are awesome thanks
