### ISSUE TITLE
Suggestion: PhotoView Sample app could combine both sample activities, acting on the current image in PageView

### ISSUE THREAD

**Issue by RoundSparrow** [chrisbanes/PhotoView#323]
Has anyone tried to combine the two modes of the PhotoView Sample app?  I am thinking of a third choice: ViewPager that allows all the actions on a single image.

While in the ViewPager mode, it would be nice to be able to long-click or otherwise activate a context-sensitive menu on individual items... I know that might be difficult due to the press interception and confusion over context.  Perhaps this would be an ideal case for a FloatingActionButton that could be enabled and disabled from the Activity menu?

**Comment by Lakshmisai94** [comment]
How to resolve this issue plz respond quickly and send me the link to resolve issue

**Comment by Lakshmisai94** [comment]
PhotoView Sample app could combine both sample activities, acting on the current image in PageView #323.
How to resolve the above one

**Comment by Jawnnypoo** [comment]
Feel free to make a pull request to add this if you want it
