### ISSUE TITLE
How to get onClick() or onTouch() event on ImageView (with which PhotoViewAttacher is initialized)

### ISSUE THREAD

**Issue by abhishekagra** [chrisbanes/PhotoView#325]
I am using PhotoView library (https://github.com/chrisbanes/PhotoView) with Picasso in ViewPager to display image with zoom in/out feature. I need to hide system bars on tapping(clicking) over image, but I am not able to get neither onClick() event nor onTouch() event on ImageView.

**Comment by sreejithraman** [comment]
You want to use the onViewTapListener() in the PhotoViewAttacher.
````java
PhotoViewAttacher attacher = new PhotoViewAttacher(imageView);
attacher.setOnViewTapListener(this);
````

**Comment by Jawnnypoo** [comment]
Yep, thanks @sreejithraman
