### ISSUE TITLE
View pager ontouch listener not working

### ISSUE THREAD

**Issue by gurugps** [chrisbanes/PhotoView#326]
Create view pager with photo view.
And set onTouch listener for viewpager.
There is no any response inside touch listener.

**Comment by sreejithraman** [comment]
You want to use the onViewTapListener() in the PhotoViewAttacher.
````java
PhotoViewAttacher attacher = new PhotoViewAttacher(imageView);
attacher.setOnViewTapListener(this);
````

**Comment by Jawnnypoo** [comment]
Thanks @sreejithraman
