### ISSUE TITLE
onPhotoTapListener does not work when reuse photoview

### ISSUE THREAD

**Issue by HuangHanquan** [chrisbanes/PhotoView#328]
onPhotoTapListener does not work when reuse photoview becase of clearup method invoked in onDetachedFromWindow method.

**Comment by Jawnnypoo** [comment]
If the PhotoViewAttacher has called cleanup, then you should not expect that OnPhotoTapListener to work anymore. It sounds like there might be deeper issues. Once cleanup is called, the ImageView should no longer be visible
