### ISSUE TITLE
I need help to solve this game bug

### ISSUE THREAD

**Issue by sniperassault** [chrisbanes/PhotoView#330]
Hi everyone,
I need help to solve a bug with the old gameloft games on android ICS and higher
the problem appear when i making a multitouch action while I run the game, then the game gives me force close. I noticed in the logcat and this is the error:
`1-03 16:48:15.726 E/AndroidRuntime( 4860): FATAL EXCEPTION: main
01-03 16:48:15.726 E/AndroidRuntime( 4860): java.lang.IllegalArgumentException: pointerIndex out of range
01-03 16:48:15.726 E/AndroidRuntime( 4860): at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-03 16:48:15.726 E/AndroidRuntime( 4860): at android.view.MotionEvent.getX(MotionEvent.java:197 4)
01-03 16:48:15.726 E/AndroidRuntime( 4860): at com.gameloft.android.TBFV.GloftGMHP.ML.GameGLSurfa ceView.onTouchEvent(GameGLSurfaceView.java:285)
01-03 16:48:15.726 E/AndroidRuntime( 4860): at android.view.View.dispatchTouchEvent(View.java:554 1).`

it is clear that this bug does not happen to me when I run the game in android 2.3 or lower
I would like to know if someone knows the way to fix this either modifying the app or modifying the android system.

thanks for your attention and I hope answers

**Comment by Jawnnypoo** [comment]
What does this have to do with this library?
