### ISSUE TITLE
fail compile 

### ISSUE THREAD

**Issue by MohamadFtah** [chrisbanes/PhotoView#335]
hi !! ,
when I compile "compile 'com.commit451:PhotoView:1.2.5' ".
I get this error:
failed to resolve com.android.support:support-v4:23.2.1 .
I don't know why its really annoying can't fix it. help

**Comment by Jawnnypoo** [comment]
You need to download the latest support library

**Comment by MohamadFtah** [comment]
done , But I still keep getting the error

**Comment by michaeljakob** [comment]
Same
