### ISSUE TITLE
Use of deprecated methods in onSingleTapConfirmed DefaultOnDoubleTapListener

### ISSUE THREAD

**Issue by veyndan** [chrisbanes/PhotoView#343]
After deprecating the methods `getOnPhotoTapListener` and `getOnViewTapListener`, the source code hasn't been modified to accommodate these changes. I can fix this in the future, but I don't have much time over the next few weeks. So if anyone wants to fix this in the meantime, please feel free to, but I just wanted to bring it to your attention.

**Comment by Jawnnypoo** [comment]
What do you mean the source code hasn't changed?

**Comment by veyndan** [comment]
As both these methods have now been deprecated (and my assumption is that these will be removed in a build in the future), any use of these methods should be removed from the source code and be modified in order to work as it currently does. In the current state, the source code hasn't been modified to remove all the references to these methods.

**Comment by Jawnnypoo** [comment]
Ahh, I see. Yes, this does need to be done. Thanks

**Comment by veyndan** [comment]
I was just about to remove the internal dependency on `getOnPhotoTapListener()` and `getOnViewTapListener()` but it appears that you have un-deprecated(?) these methods. Has the consensus on the deprecation of these two methods changed? It is possible just to convert these methods to package local, so the benefits of not exposing this method to the user is gained and another benefit is the lack of use of deprecated methods in the library source.

**Comment by Jawnnypoo** [comment]
Yeah, making them package local is a good idea. Go for it. I am thinking that the next release with be a major release so feel free to modify as needed
