### ISSUE TITLE
I want know scale event cancel  's callback

### ISSUE THREAD

**Issue by luhaoaimama1** [chrisbanes/PhotoView#346]
because when scale event  smaller than minimumScale  to cancel .The ViewPager Activity is cancel  to return show small pic Activity; or I set minimumScale 0.3 but is 0.5 .IF now  is 0.3 and scale event cancel I will restore to 0.5 ,you know  this is my thinking because I often look this style. so I want scale event cancel 's callback

**Comment by Jawnnypoo** [comment]
Feel free to submit a pull request adding this feature if you would like it
