### ISSUE TITLE
[Feature request] rotate image by two fingers

### ISSUE THREAD

**Issue by ywwynm** [chrisbanes/PhotoView#347]
Can we add a new feature that allows user to rotate the image by two fingers? The gesture is, put a finger on the screen as the center of a "divider", then draw an arch using another finger. It's very cool and useful, isn't it?

**Comment by Jawnnypoo** [comment]
As far as I understand, this is supported? It sounds like you are just describing pinch zoom

**Comment by ywwynm** [comment]
@Jawnnypoo No, the key feature is rotating the image. It seems that PhotoView allows user to zoom in/out an image but not to rotate it.

**Comment by Jawnnypoo** [comment]
Ohhh, right. Rotation is out of the scope of this library. Feel free to make a pull request if you have an idea of how to achieve it, but it will not be added
