### ISSUE TITLE
addListener --> Replacement listener?

### ISSUE THREAD

**Issue by PGMacDesign** [chrisbanes/PhotoView#354]
Good day, I received some inherited code for a project and am in the process of updating dependencies as many are outdated. When I updated photo view, I broke a section of code that looked like this:

        mImageView.addListener(new IGetImageBounds() {

            @Override
            public Rect getImageBounds() {
                return new Rect((int) Edge.LEFT.getCoordinate(), (int) Edge.TOP.getCoordinate(), (int) Edge.RIGHT
                        .getCoordinate(), (int) Edge.BOTTOM.getCoordinate());
            }
        });

From what I have researched, this was changed entirely, but I am having trouble figuring out what it morphed TO. How should I change this code (addListener and the new listener within) so that it will no longer throw compile errors, but will match what the newer version of this code is? 

Thanks for your time, 
-PGMacDesign

**Comment by Jawnnypoo** [comment]
Do you mind telling me what version of the library it was previously before updating?

**Comment by PGMacDesign** [comment]
Sadly, it looks like they forked the project and just included it in its entirety, I don't see a version listed. Is there an easy way to find it within forked code?

**Comment by Jawnnypoo** [comment]
Not really, besides to look back at the git history. I am guessing that listener was completely custom. I have no idea what bounds it is talking about so I don't think I can help you out much

**Comment by PGMacDesign** [comment]
I appreciate the response J! Thanks for your time.
