### ISSUE TITLE
PhotoView objects does not work with BottomSheets swipe up gesture

### ISSUE THREAD

**Issue by wightwulf1944** [chrisbanes/PhotoView#358]
When using a PhotoView inside a coordinator layout that also has a BottomSheet, the swipe up gesture is consumed by the PhotoView; preventing the BottomSheet from showing.

Replacing the PhotoView with an ImageView in the example below fixes the issue.

PhotoView works well with a ViewPager that may use a swipe left/right gesture but does not work with a BottomSheet swipe up gesture.

___
Example below requires Glide 3 and android support library 23.2.1

**Class:**
```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Glide.with(this)
                .load("http://danbooru.donmai.us/data/8bacc97285c1b78cedca8666b07aa887.png")
                .into((PhotoView) findViewById(R.id.photoView));
    }
}
```

**Layout (activity_main.xml):**
```
<android.support.design.widget.CoordinatorLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <uk.co.senab.photoview.PhotoView
        android:id="@+id/photoView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center" />

    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ac dignissim ex. Aliquam sit amet ligula in justo mollis euismod."
        app:layout_behavior="android.support.design.widget.BottomSheetBehavior" />

</android.support.design.widget.CoordinatorLayout>
```

**Comment by wightwulf1944** [comment]
This issue is no longer relevant with the latest support library. If you encounter this issue please update your support library.

**Comment by PkmX** [comment]
This does not seem to work even with the latest support library.

I'm using the latest AndroidX, PhotoView 2.3.0 and a `LinearLayout` with Google's `com.google.android.material.bottomsheet.BottomSheetBehavior` all inside a `CoordinatorLayout`.

**Comment by dream-space** [comment]
I am also face same issue, but for specific android version, I try buttomSheet on android M but not working try buttomSheet on android P working

**Comment by dilipsuthar1997** [comment]
The **bottom sheet** is not working when I use **PhotoView** library.
When I swipe up on bottom sheet it's not going to up and show an error.
**activity_photo_detail.xml**
`<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:tools="http://schemas.android.com/tools"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="?attr/backgroundColor"
        tools:context=".activity.PhotoDetailActivity">

    <androidx.appcompat.widget.Toolbar
            android:id="@+id/toolbar"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="start|center_vertical"
            android:background="@drawable/gradient_overlay_toolbar"
            android:fitsSystemWindows="true"
            android:elevation="1dp"
            android:theme="@style/ThemeOverlay.MaterialComponents"
            app:popupTheme="@style/ThemeOverlay.MaterialComponents">
        <androidx.constraintlayout.widget.ConstraintLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content">
            <com.mikhaellopez.circularimageview.CircularImageView
                    android:id="@+id/image_user_profile"
                    android:layout_width="35dp"
                    android:layout_height="35dp"
                    app:civ_border_width="0dp"
                    tools:src="@drawable/placeholder_profile"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    android:transitionName="profilePhoto"/>

            <TextView
                    android:id="@+id/text_photo_by"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:textColor="@color/white"
                    tools:text="beccatapert"
                    app:layout_constraintStart_toEndOf="@+id/image_user_profile"
                    android:layout_marginStart="8dp"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintTop_toTopOf="parent"
                    app:layout_constraintEnd_toStartOf="@+id/text_likes"
                    android:layout_marginEnd="8dp"
                    android:transitionName="profileName"/>
        </androidx.constraintlayout.widget.ConstraintLayout>
    </androidx.appcompat.widget.Toolbar>

    <com.github.chrisbanes.photoview.PhotoView
            android:id="@+id/image_photo"
            android:background="?attr/colorPrimaryDark"
            android:scaleType="centerCrop"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:transitionName="photo"/>

    <com.google.android.material.floatingactionbutton.FloatingActionButton
            android:id="@+id/fab"
            android:layout_gravity="bottom|end"
            android:layout_margin="16dp"
            android:src="@drawable/ic_nav_about"
            android:tint="@color/white"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

    <include layout="@layout/bottom_sheet_photo_detail"/>

</androidx.coordinatorlayout.widget.CoordinatorLayout>`

**Comment by wightwulf1944** [comment]
disclaimer: i'm not part of PhotoView's development team

For those that are still encountering this issue even when using the latest support/androidx library and would like to receive some help it would be best to include a **minimal and reproducible example**.

You also have to somehow prove that the issue is caused by PhotoView by checking if the issue manifests when you replace the PhotoView with an ImageView in your minimal and complete example.

[For more information see this stackoverflow guide.](https://stackoverflow.com/help/minimal-reproducible-example) I'll be unsubscribing from this issue now.
