### ISSUE TITLE
PhotoView movement causes RecyclerView cell background to disappear

### ISSUE THREAD

**Issue by ziranshang** [chrisbanes/PhotoView#364]
I have a RecyclerView with an item that has a PhotoView. If the user scrolls the RecyclerView while an animation/movement is occurring in the PhotoView (for example, if the user flings the zoomed in PhotoView and then scrolls the RecyclerView immediately after), the background of the RecyclerView cell disappears/becomes transparent.

**Comment by Jawnnypoo** [comment]
Can you test this with a normal ImageView and see if it occurs then too?

**Comment by Jawnnypoo** [comment]
I am doubting this is related to this library
