### ISSUE TITLE
I need help in image location in ImageView using PhotoView

### ISSUE THREAD

**Issue by nexxie** [chrisbanes/PhotoView#366]
I need help in image location in ImageView using PhotoView. And i whant to pull up the text below ImageView
XML:
`<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.NestedScrollView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    app:layout_behavior="@string/appbar_scrolling_view_behavior"
    tools:context="com.example.nexxie.diplom2.Eur_S10_ALL_E_001"
    tools:showIn="@layout/activity_eur__s10__all__e_001">

    <RelativeLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content">

        <ImageView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:scaleType="matrix"
            android:id="@+id/eur__e__s10__all_001"
            android:layout_alignParentLeft="true"
            android:layout_alignParentStart="true" />

        <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="?android:attr/textAppearanceSmall"
        android:text="@string/s10100BA270"
        android:id="@+id/textView2"
        android:layout_below="@+id/textView"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true" />

        <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textAppearance="?android:attr/textAppearanceSmall"
        android:text="@string/s10100BA260"
            android:layout_below="@+id/eur__e__s10__all_001"
        android:id="@+id/textView"
        android:layout_alignParentLeft="true"
        android:layout_alignParentStart="true"
        />

    </RelativeLayout>

</android.support.v4.widget.NestedScrollView>
`

ScreenShot

[http://cs630027.vk.me/v630027690/2d5ee/4GkQkkFq3_4.jpg](url)

**Comment by Jawnnypoo** [comment]
I have no idea what you are asking for here, and I cannot view that image. Are you asking how to place an image in XML? Please check the README for usage

**Comment by nexxie** [comment]
![4gkqkkfq3_4](https://cloud.githubusercontent.com/assets/5469847/15505860/e14fedb4-21cd-11e6-8406-6ae01e814864.jpg)
I want to move up ImageView and pull 2 TextView under this  ImageView

**Comment by Jawnnypoo** [comment]
In that case, you will want to use a LinearLayout as your root layout instead of a RelativeLayout, with your orientation set to vertical
