### ISSUE TITLE
After adding PhotoView to the project: com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry

### ISSUE THREAD

**Issue by alfredbaudisch** [chrisbanes/PhotoView#370]
After I added PhotoView to the project, it won't build anymore.

	FAILURE: Build failed with an exception.

	* What went wrong:
	Execution failed for task ':fred:transformClassesWithJarMergingForDebug'.
	> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: uk/co/senab/photoview/BuildConfig.class

	* Try:
	Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

	BUILD FAILED

	Total time: 2.582 secs

Gradle:

    allprojects {
        repositories {
            jcenter()
            maven { url "https://repo.commonsware.com.s3.amazonaws.com" }
            maven { url "https://jitpack.io" }
        }
    }
    
    dependencies {
        compile fileTree(include: ['*.jar'], dir: 'libs')
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:appcompat-v7:23.2.1'
        compile 'com.android.support:design:23.2.1'
        compile 'com.android.support:support-v4:23.2.1'
        compile 'com.github.bumptech.glide:glide:3.7.0'
        compile 'net.hockeyapp.android:HockeySDK:3.7.1'
        compile 'jp.wasabeef:glide-transformations:2.0.0'
        compile 'com.github.chrisbanes:PhotoView:1.2.6'
        compile 'com.android.support:cardview-v7:23.3.0'
        compile 'com.android.support:recyclerview-v7:23.3.0'
        compile 'com.amirarcane.recent-images:recentimages:1.0.2'
        compile 'net.yazeed44.imagepicker:imagepicker:1.3.0'
    }

I found a similar issue in the Issues already, but there is no related at all.

**Comment by Jawnnypoo** [comment]
Only thing I could think is that one of those other dependencies that you are pulling in also depend on PhotoView. You should check and see using the gradle command
https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#para:commandline_dependency_report

**Comment by alfredbaudisch** [comment]
I actually solved after creating the issue, sorry for not updating before.

The Image Picker depends on PhotoView: 
`compile 'net.yazeed44.imagepicker:imagepicker:1.3.0'`

**Comment by JamesLiAndroid** [comment]
Maybe you have a library in the libs directory ,and you imported it from build.gradle(:app), so try to save one condition!
