### ISSUE TITLE
Rounded Image

### ISSUE THREAD

**Issue by nicolabeghin** [chrisbanes/PhotoView#371]
Hi
I would like to know if it's possible to access/implement any kind of rounding on the image itself. Like merging the features of this project with com.makeramen.roundedimageview.RoundedImageView.

I know this would require customizing PhotoView, but at least I would know it's something feasible.

thanks
nicola

**Comment by Jawnnypoo** [comment]
Sure, you could accomplish this by extending RoundedImageView and giving it a PhotoViewAttacher and implementing all the same methods that PhotoView does.

**Comment by nicolabeghin** [comment]
Just as a hint for anyone facing the same requirement: much easier to use a wrapping CardView with rounded borders!
