### ISSUE TITLE
No more travis build

### ISSUE THREAD

**Issue by k3b** [chrisbanes/PhotoView#375]
when i look at https://travis-ci.org/chrisbanes/PhotoView/branches the last travis build is more than 9 months old. Is disabling travis-ci build on purpose?

The current developbranch has a version mismatch travis <-> gradle which should be fixed with https://github.com/chrisbanes/PhotoView/pull/373/commits/be9cd50ffd9035ec3277993190a874db7b0da62f

**Comment by Jawnnypoo** [comment]
Since I do not own this project on GitHub, I cannot really do anything about this
