### ISSUE TITLE
Error:Could not find com.github.chrisbanes:PhotoView:1.2.6.

### ISSUE THREAD

**Issue by JakeWoki** [chrisbanes/PhotoView#377]

**Comment by omerjerk** [comment]
I'm also having this.

**Comment by George-Soros** [comment]
I'm also having this.

**Comment by George-Soros** [comment]
我解决了，就是还要先配置下面的，再去compile 'com.github.chrisbanes:PhotoView:1.2.6'
repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }

**Comment by Jawnnypoo** [comment]
Instructions are in the README

**Comment by boboyuwu** [comment]
我配置了这些还是不行
 Error:Failed to resolve: annotationProcessor
 Failed to resolve: com.github.chrisbanes:PhotoView:latest.release.here

**Comment by Jawnnypoo** [comment]
Replace `latest.release.here` with the latest release

**Comment by frgrz** [comment]
implementation 'com.github.chrisbanes.photoview:library:X.X.X

**Comment by Shivaratnakumar** [comment]
@Jawnnypoo Your suggestion worked for me.Thanks.
