### ISSUE TITLE
Bitmap too large to be uploaded into a texture error

### ISSUE THREAD

**Issue by venkat20390** [chrisbanes/PhotoView#378]
Whenever i load high quality photos and zoom the photos. I am getting Bitmap too large to be uploaded into a texture error and the image view background is hidden. After that only the blank image view is being shown.

**Comment by zhangsr** [comment]
https://github.com/chrisbanes/PhotoView/issues/53

**Comment by k3b** [comment]
This should be fixed with #373

**Comment by Jawnnypoo** [comment]
Take a look at this library, which supports subsampling https://github.com/davemorrissey/subsampling-scale-image-view
