### ISSUE TITLE
Progaurd rules

### ISSUE THREAD

**Issue by alkesh-iproperty** [chrisbanes/PhotoView#388]
Note: the configuration keeps the entry point 'uk.co.senab.photoview.PhotoView { void setOnMatrixChangeListener(uk.co.senab.photoview.PhotoViewAttacher$OnMatrixChangedListener); }', but not the descriptor class 'uk.co.senab.photoview.PhotoViewAttacher$OnMatrixChangedListener'
Note: the configuration keeps the entry point 'uk.co.senab.photoview.PhotoView { void setOnPhotoTapListener(uk.co.senab.photoview.PhotoViewAttacher$OnPhotoTapListener); }', but not the descriptor class 'uk.co.senab.photoview.PhotoViewAttacher$OnPhotoTapListener'
Note: the configuration keeps the entry point 'uk.co.senab.photoview.PhotoView { void setOnViewTapListener(uk.co.senab.photoview.PhotoViewAttacher$OnViewTapListener); }', but not the descriptor class 'uk.co.senab.photoview.PhotoViewAttacher$OnViewTapListener'
Note: the configuration keeps the entry point 'uk.co.senab.photoview.PhotoView { void setOnScaleChangeListener(uk.co.senab.photoview.PhotoViewAttacher$OnScaleChangeListener); }', but not the descriptor class 'uk.co.senab.photoview.PhotoViewAttacher$OnScaleChangeListener'
Note: the configuration keeps the entry point 'uk.co.senab.photoview.PhotoView { void setOnSingleFlingListener(uk.co.senab.photoview.PhotoViewAttacher$OnSingleFlingListener); }', but not the descriptor class 'uk.co.senab.photoview.PhotoViewAttacher$OnSingleFlingListener'

**Comment by Jawnnypoo** [comment]
Those are just warnings, it should compile just fine with proguard with no need for additional rules
