### ISSUE TITLE
PhotoView gets in front of FAB

### ISSUE THREAD

**Issue by FedePeralta** [chrisbanes/PhotoView#389]
Im displaying an image view on the content layout which is included in one activity layout. this activity layout contains a red floating action button, whenever the photo is attached to PhotoView Attacher, the fab goes behind the image view.
What can I do? Is there a way to let fab be "always on top" or the image "always on botton"?

![c2714de0-48bd-4809-92bb-a776a7beef6b](https://cloud.githubusercontent.com/assets/19721178/16928277/c35cec78-4cff-11e6-83af-a53ef457d945.jpg)

**Comment by Jawnnypoo** [comment]
The order is defined by the order you add the views to the ViewGroup, aka if you add it last in the XML, it will be on top. On 5.0+, the elevation also has an effect on the order that views display. So, adjust each of these values and it should resolve this
