### ISSUE TITLE
Gradle dependency not able to compile

### ISSUE THREAD

**Issue by abhishekjain885** [chrisbanes/PhotoView#391]
Error:(32, 13) Failed to resolve: com.github.chrisbanes:PhotoView:1.2.6

**Comment by Jawnnypoo** [comment]
Do you have an error message or log you can post here?

**Comment by quetzalarc** [comment]
i'm to get error

Error:(30, 13)
Failed to resolve: com.github.chrisbanes:PhotoView:1.2.6

**Comment by mazzonem** [comment]
May I suggest to follow the readme section called **Gradle Dependency**: https://github.com/chrisbanes/PhotoView
And make sure you added the jitpack repo :)

**Comment by justicevita** [comment]
I think you should add " maven { url "https://jitpack.io" }" to your  root build.gradle file,just follow **Gradle Dependency**

**Comment by Jawnnypoo** [comment]
Yep, thats the trick
