### ISSUE TITLE
Cannot Sync the Project with Gradle

### ISSUE THREAD

**Issue by sghazagh** [chrisbanes/PhotoView#395]
Added the dependency (compile 'com.github.chrisbanes:PhotoView:1.2.7') and try to rebuild the project.
Receive this error:

Error:(30, 13) Failed to resolve: com.github.chrisbanes:PhotoView:1.2.7
Show in File
Show in Project Structure dialog

**Comment by Jawnnypoo** [comment]
In the readme, it also mentions adding jitpack. Have you done this?

**Comment by sghazagh** [comment]
Sorry mate, my mistake. Hadn't got that part.
It's syncing now.

Thank you

**Comment by Jawnnypoo** [comment]
No prob
