### ISSUE TITLE
bug onDetachedFromWindow

### ISSUE THREAD

**Issue by Presleyzheng** [chrisbanes/PhotoView#406]
if load image with ImageLoader，and the task is loading ,i finish acitivty who with [PhotoView](https://github.com/chrisbanes/PhotoView/blob/master/library/src/main/java/uk/co/senab/photoview/PhotoView.java)  and set the listener with loading like below:
`ImageLoader.getInstance().displayImage(url, new ImageView(), new SimpleImageLoadingListener() {          
            public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
                view.setOnLongClickListener(listener)//crash with NullPointException;
            }
 });`
before loading complete if the view is detached from window.

i think onDetachedFromWindow should not set `mAttacher = null`

**Comment by Jawnnypoo** [comment]
Is this within a fragment? If so, you should check `if (getView() != null)` before setting the on long click listener

**Comment by Presleyzheng** [comment]
it is caused by that i use it in ViewPager within an activity, and reuse the [PhotoView](https://github.com/chrisbanes/PhotoView/blob/master/library/src/main/java/uk/co/senab/photoview/PhotoView.java) object which like the item reuse in listview

**Comment by Jawnnypoo** [comment]
This is a leak if you are still referencing a view after an async operation completes, you need to check and see if the UI is still relevant before modifying it
