### ISSUE TITLE
PhotoView zoom resets when system UI visibility changes

### ISSUE THREAD

**Issue by FaultException** [chrisbanes/PhotoView#409]
It seems to be because setFrame() is called when the system UI visibility changes and that calls update() regardless of whether the frame actually changed. (In my case, the system UI is stable so it doesn't.)

Possible fixes:
- Make setFrame() not call update() if the bounds don't change. This would only work if the system UI was stable. Or:
- Make update() retain the same relative scale when possible.

If needed, I could submit a pull-request to implement the first option, however I don't know enough about the internals to do the second.

Thanks.

**Comment by happylishang** [comment]
maybe , you can try not override setFrame in your PhotoView.java
`
    @Override
//    protected boolean setFrame(int l, int t, int r, int b) {
//        boolean changed = super.setFrame(l, t, r, b);
//        if (null != mAttacher) {
//            mAttacher.update();
//        }
//        return changed;
//    }
`

**Comment by FaultException** [comment]
I already fixed it locally by making setFrame only call update if the changed variable is true. I'm hoping it can be fixed in the official implementation so I don't have to keep a copy of PhotoView around in my source.

**Comment by hscissors** [comment]
Did this ever get fixed?

**Comment by hyne-shan** [comment]
if (changed && null != mAttacher) {
            mAttacher.update();
         }


this code have issue when use sharedElement

**Comment by hyne-shan** [comment]
i find a good solution when use sharedElement

 @Override
    public Matrix getImageMatrix() {

        mAttacher.update();

        return mAttacher.getImageMatrix();
    }

if you have a same problem   you can try it

**Comment by franzks** [comment]
Also experienced this bug. I'm using the Android Databinding library and if ever I update any TextView's text via databinding the PhotoView also seems to "reset". Same behavior when I tried to update a FloatingActionButton's visibility (also via databinding) to and from GONE, but it seems to and from INVISIBLE doesn't trigger a setFrame(). Followed @FaultException and I reluctantly have a local copy of PhotoView. Hoping it can be fixed in the official repo!

**Comment by FaultException** [comment]
@hyne-shan What issue does that cause with shared elements?

**Comment by hyne-shan** [comment]
@FaultException  The animation will shake

**Comment by Jawnnypoo** [comment]
This is fixed now
