### ISSUE TITLE
23.11 版本以上会冲突

### ISSUE THREAD

**Issue by s162738** [chrisbanes/PhotoView#412]
compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:design:23.1.1'
    compile 'com.android.support:cardview-v7:23.1.1'

亲测一个非常奇葩的问题。。。使用23.1.1以上版本（不包含23.1.1）。

在fragment 中使用  <android.support.design.widget.CollapsingToolbarLayout>  会报错

Error inflating class android.support.design.widget.CollapsingToolbarLayout

在activity 中则不会报错。。

**Comment by Jawnnypoo** [comment]
I have no idea what you are asking here and I do not think it has anything to do with this library

**Comment by s162738** [comment]
sorry,   I just want to ask, when I use 23.1.1 above （Does not contain 23.1.1）。In the fragment ， The use of the CollapsingToolbarLayout layout file。
 Complains "Error inflating class android. Support. The design. The widget. CollapsingToolbarLayout"
remove this library  is not an error。

**Comment by youyuge34** [comment]
因为依赖树产生了冲突，photoview会引入高版本support包，exclude即可。
可参考 http://www.jianshu.com/p/8d02da77c83d
