### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by s162738** [chrisbanes/PhotoView#413]
![m mn cvlax c dzb r 8p7](https://cloud.githubusercontent.com/assets/20291704/18047117/c0eb7fc0-6e0d-11e6-8c7e-e6ea554be725.png)

**Comment by Jawnnypoo** [comment]
Can you explain what this issue has to do with the PhotoView library? There is no mention of it in the stacktrace

**Comment by Jawnnypoo** [comment]
This is the issues section for the PhotoView library, please do not post unrelated issues here. Post this on something like StackOverflow to get support from the community.

**Comment by s162738** [comment]
can use give me a email? I am sure it's your problem。
now, I use "photoView-library-1.2.4"  ,it's no problem.
