### ISSUE TITLE
Use viewpager time, when the zoom size is smaller than imageview original size, it will throw an exception

### ISSUE THREAD

**Issue by uglyer** [chrisbanes/PhotoView#414]
Use viewpager time, when the zoom size is smaller than imageview original size, it will throw an exception.
And when used alone, this can work.

Or see this video: http://com.com.sb/upload/fd7cc3e7c3792d7f4052cc2dc555427a.mp4

FATAL EXCEPTION: main
Process: com.xxxx, PID: 8362
java.lang.IllegalArgumentException: pointerIndex out of range
   at android.view.MotionEvent.nativeGetAxisValue(Native Method)
   at android.view.MotionEvent.getX(MotionEvent.java:2069)

**Comment by Jawnnypoo** [comment]
Take a look at the section in the README about problematic ViewGroups

**Comment by uglyer** [comment]
Thx,did not look carefully.
