### ISSUE TITLE
problem to integrate Admob to PhotoView app 

### ISSUE THREAD

**Issue by benza86** [chrisbanes/PhotoView#417]
I am trying to integrate Admob to PhotoView, i end up with no success.
who can help me?

**Comment by Jawnnypoo** [comment]
What exactly is the issue you are facing?

**Comment by benza86** [comment]
I want to integrate adview and interstetial to this app like 
https://s3.amazonaws.com/adiante-adianteapps/resources/info_images/104/image/admob_small.png
but I have some problems :+1: 
first: no relative layout 
second:Error:Execution failed for task ':sample:processDebugManifest'. > Manifest merger failed : uses-sdk:minSdkVersion 8 cannot be smaller than version 9 declared in library [com.google.android.gms:play-services-ads:8.4.0] C:\code android 2016\sncft admob\PhotoView-master\sample\build\intermediates\exploded-aar\com.google.android.gms\play-services-ads\8.4.0\AndroidManifest.xml Suggestion: use tools:overrideLibrary="com.google.android.gms.ads" to force usage
can you integrate admob and send methe source code?

**Comment by Jawnnypoo** [comment]
You need to set your apps minSdk to 9, since that is the minimum that the libraries you are using uses. This issue tracker is dedicated to providing support to people who use PhotoView and log issues with the library, not for general support.
