### ISSUE TITLE
Using hackylayout doesnt work.

### ISSUE THREAD

**Issue by aalap03** [chrisbanes/PhotoView#418]
I have the same outof range exception and I read your readme and problem was in viewpager layout so I created the class as mentioned extending viewpager, and changed xml tag of my view pager to hackylauout class but in gives me error when I run that xml it doesnt able to find the class hackylayout. It gives inflateexecption..

**Comment by Jawnnypoo** [comment]
Okay, you probably have the name of the layout incorrect in your XML. You can copy the HackyViewPager from the sample project and put it in your project and it will work fine.
