### ISSUE TITLE
1.3.0 NullPointerException in PhotoViewAttacher.getScaleType()

### ISSUE THREAD

**Issue by shaodong618** [chrisbanes/PhotoView#419]
my app use ViewPager + PhotoView, to see a few picture, the app crash.
version 1.2.6 not

java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.ImageView$ScaleType uk.co.senab.photoview.PhotoViewAttacher.getScaleType()' on a null object reference
at uk.co.senab.photoview.PhotoView.getScaleType(PhotoView.java:115)

**Comment by shaodong618** [comment]
I compile PhotoView.class in version 1.2.6 and 1.3.0,

`    @Override
    protected void onDetachedFromWindow()
    {
        mAttacher.cleanup();
// Annotate this line of code to solve the problem
//        mAttacher = null;
        super.onDetachedFromWindow();
    }`

**Comment by Jawnnypoo** [comment]
Sounds like you are using the attacher after the view has been detached, so it is an issue in your code and not with the library

**Comment by luyangliu616** [comment]
shaodong618 thanks

**Comment by passself** [comment]
how to resolve this problem?
