### ISSUE TITLE
I have a problem about this project when  set “minifyEnabled true”  

### ISSUE THREAD

**Issue by longeleven** [chrisbanes/PhotoView#420]
Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.

> java.io.IOException: Can't write [/Users/mac/Desktop/android_doc/Crayfish/app/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar](Can't read [/Users/mac/Desktop/android_doc/Crayfish/app/build/intermediates/exploded-aar/com.github.chrisbanes/PhotoView/1.3.0/jars/classes.jar%28;;;;;;**/*.class%29] %28Duplicate zip entry [classes.jar:uk/co/senab/photoview/PhotoViewAttacher$1.class]%29)

**Comment by eodonnell21** [comment]
BOO HOO DOING IT RIGHT OR YOUR FUCKING RETARDED AND ALL AROUND JUST DUMB AND STUPID #CATHOLICRASTAFARIANISM

**Comment by knjin** [comment]
`-keep class uk.co.senab.photoview.** { *; } #photoview`

I add this in **proguard-rules.pro**

**Comment by Jawnnypoo** [comment]
Looks like you are using a library that has the files of PhotoView contained within the library, as well as including PhotoView as a dependency. Go through your list of libraries and see which might have this. It is not a ProGuard issue.
