### ISSUE TITLE
Medical marijuana in Pennsylvania

### ISSUE THREAD

**Issue by eodonnell21** [chrisbanes/PhotoView#424]
Medical Marijuana and Recreational CANNABIS  HELP.ME TO NOT DO AS MANY PAIN PILLS, WHEN I HAVE MY MEDICAL CANNABIS I CAN DO ONLY 1 pain pill and not 3 like I need without my  #CANNABIS, so let's get this up and running PENNSYLVANIA I HAVE CROHN'S DISEASE AND SEVERE IBSD WHICH CRIPPLES ME OVER IN PAIN ON A DAILY BASIS...SUCKS

**Comment by Jawnnypoo** [comment]
This is a highly inappropriate place for these issues and comments you are making. Stop
