### ISSUE TITLE
How can I use it for a ViewGroup?

### ISSUE THREAD

**Issue by serdarbuyukkanli** [chrisbanes/PhotoView#426]
I want to zoom in/out to 2 views at the same time with the same zoom scale. Views are on a RelativeLayout, one overlaid of the other. Can I make it with this library?

**Comment by shineon84** [comment]
@serdarbuyukkanli i have to do the same! did you solve your problem?

**Comment by serdarbuyukkanli** [comment]
Hi, i couldn't solve it.

**Comment by shineon84** [comment]
Thank you anyway :)

**Comment by serdarbuyukkanli** [comment]
Good luck with it :)

**Comment by Jawnnypoo** [comment]
This is beyond the scope of this library
