### ISSUE TITLE
why is this? can not resolve 

### ISSUE THREAD

**Issue by wzyzb** [chrisbanes/PhotoView#429]
Error:(47, 13) Failed to resolve: com.github.chrisbanes:PhotoView:1.3.0
<a href="openFile:/Users/bob/git_repository/ExoPlayer/demo/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Jawnnypoo** [comment]
Check the README and make sure you are properly adding the Jitpack url

**Comment by oldergod** [comment]
make sure jitpack is inside `allprojects`, not `buildscript`.
