### ISSUE TITLE
Detatch PhotoView / undo attaching

### ISSUE THREAD

**Issue by Voyz** [chrisbanes/PhotoView#430]
Is there a way to undo attaching PhotoViewAttacher to an ImageView? Or temporarily disabling it? So that the ImageView would behave back as if it wasn't modified by the PhotoView? I'm facing some issues when doing measurements on the attached ImageView programatically.

**Comment by HsuYee** [comment]
Hi,
mAttacher.cleanup() might work. It seems to remove the imageView from the attacher.
I also needed to disable the attacher based on some conditions. So, I checked the condition and detach/ attach the imageView accordingly. Its indicated as /deprecation/ tho.

**Comment by Jawnnypoo** [comment]
Does `photoView.setZoomable(false);` not cover your needs?

**Comment by MJonesDev** [comment]
For some reason, .cleanup does not work for me anymore. After updating to the latest version, it shows it as "cannot resolve".

**Comment by Jawnnypoo** [comment]
`setZoomable` is what we support, if you need anything more than that, it would be best to fork
