### ISSUE TITLE
Sync project  and Error:(110, 14)  Failed to resolve: com.github.chrisbanes:PhotoView:1.3.0 

### ISSUE THREAD

**Issue by PongPloy2016** [chrisbanes/PhotoView#433]
i use Sign project to 'com.github.chrisbanes:PhotoView:1.3.0 and use 

 repositories {

        maven { url "https://jitpack.io" }
    }

and Erorro log 
Error:(110, 14) Failed to resolve: com.github.chrisbanes:PhotoView:1.3.0
<a href="openFile:F:/AndroidStudioProjectToCodeGears/Kubota_Android_Codegears/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by laole918** [comment]
我也遇到了同样的问题，但是我通过重启电脑解决了问题，什么原因造成的不清楚。

**Comment by Jawnnypoo** [comment]
Make sure it is in your outermost build.gradle
