### ISSUE TITLE
Build error: java.util.zip.ZipException: 

### ISSUE THREAD

**Issue by MaheshBalla461** [chrisbanes/PhotoView#437]
On adding
maven { url "https://jitpack.io" } in root build.gradle 
and
compile 'com.github.chrisbanes:PhotoView:1.3.0' in  module build.gradle
Sync success and found multiple jar files in  ...\app\build\intermediates\exploded-aar folder (in Screen shot attached).
![multiplefiles](https://cloud.githubusercontent.com/assets/22639905/19118323/b1813b3a-8b39-11e6-9be8-a26b9b19f875.PNG)

Even though the build succeeds, while trying to run the project in debug mode, I get the following error in gradle console: 

> Error:Execution failed for task ':app:packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: uk/co/senab/photoview/PhotoViewAttacher$1.class

**Comment by Jawnnypoo** [comment]
Looks like you might be importing the library twice? Can you verify that this is not the case?

**Comment by MaheshBalla461** [comment]
Found issue
We are using image picker library that is internally using photoview library.
