### ISSUE TITLE
Attempt to invoke virtual method 'android.widget.ImageView$ScaleType uk.co.senab.photoview.PhotoViewAttacher.getScaleType()' on a null object reference

### ISSUE THREAD

**Issue by akingyin1987** [chrisbanes/PhotoView#438]
uk.co.senab.photoview.PhotoView.getScaleType(PhotoView.java:115)
2 com.bumptech.glide.GenericRequestBuilder.into(GenericRequestBuilder.java:681)
3 com.bumptech.glide.DrawableRequestBuilder.into(DrawableRequestBuilder.java:448)

**Comment by funset** [comment]
i has this exception too ,do you hava Solved?

**Comment by akingyin1987** [comment]
no ,but i use  imageview is ok

**Comment by Jawnnypoo** [comment]
Sounds like you are trying to touch the attacher after it has been detached. Make sure your view still exists and is valid before doing whatever you are trying to do in Glide.

**Comment by funset** [comment]
oh if imageview has been detached it is just not visabled, how to touch?

**Comment by p4vlos** [comment]
I got this issue `Attempt to invoke virtual method 'android.widget.ImageView$ScaleType uk.co.senab.photoview.PhotoViewAttacher.getScaleType()' on a null object reference` and I am using Glide onBindViewHolder(). Where I should use Glide in a RecyclerView?
