### ISSUE TITLE
support svg?

### ISSUE THREAD

**Issue by jacky4631** [chrisbanes/PhotoView#440]
Can i  use PhotoView to load svg?

**Comment by Jawnnypoo** [comment]
Yep, since SVG can be loaded as a drawable

**Comment by atonamy** [comment]
@Jawnnypoo but can you add svg like internally in library and load from asset? So old version Androids can also render it without issues. Also android vector asset  drawable doesn't support fully featured svg files. It could be nice if your library can do at it least on level like [this](https://github.com/BigBadaboom/androidsvg) but with fast zoom and scroll render.
