### ISSUE TITLE
ImageView no longer exists. You should not use this PhotoViewAttacher any more.

### ISSUE THREAD

**Issue by LoveqLRC** [chrisbanes/PhotoView#443]
how to deal with PhotoView + PhotoViewAttacher in ViewPager?

This is the code I write in instantiateItem(ViewGroup container, int position) 
    @Override
        public Object instantiateItem(ViewGroup container, int position) {
               ......
     PhotoView  photoView = new PhotoView(PreViewActivity.this);
            MyViewAttacher attacher = new MyViewAttacher(photoView);
　　　　　　.........

}

**Comment by Jawnnypoo** [comment]
Have you taken a look at the sample? No need to create your own attacher
https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/uk/co/senab/photoview/sample/ViewPagerActivity.java
