### ISSUE TITLE
PhotoView.setImageURI doesn't show and PhotoView.setImageDrawable can't be zooming, help..

### ISSUE THREAD

**Issue by yangyiRunning** [chrisbanes/PhotoView#447]
PhotoView.setImageURI doesn't work and PhotoView.setImageDrawable can't be zooming, 
**BUT** in PhotoView.setImageResource ,use local picture is normal , **WHY???**

**Comment by Jawnnypoo** [comment]
Do not use setImageURI, please use a library like Picasso or Glide instead. setImageURI does not give you a callback in which you refresh the attacher. See the sample for an example with Picasso
