### ISSUE TITLE
setScale not functioning when animate == false unless after long delay

### ISSUE THREAD

**Issue by asos-horaceb** [chrisbanes/PhotoView#452]
I'm currently trying to use `setScale` on an image in a `ViewPager` and I'm running into some trouble.

I'm fully aware that I need to delay the calling of post and in the following example, this works as expected.
```
@Override
public PhotoView instantiateItem(ViewGroup container, int position) {
        PhotoView view = (PhotoView) getLayoutInflater().inflate(R.layout.pager_item_image, container, false);
        // Load image view image loader 
        photoView.setMaximumScale(50f);
        photoView.setMediumScale(25f);
        photoView.setMinimumScale(5f);
        photoView.post(() -> photoView.setScale(2f, true));
        container.addView(view);
        return view;
}
```
I would, however prefer not to display an animation when using `setScale` to set the initial zoom level. 
I assumed doing the above without setting `animate` or providing false would prevent the animation displaying but actually, the scale will not be set at all if `animate` is false. That is unless I set a long delay:

`photoView.postDelayed(() -> photoView.setScale(2f, true), 200);`

Then of course there's a harsh transition to the zoomed in state and it doesn't look good!
Any ideas what I'm doing wrong? 
Have I made the correct assumptions about what `setScale` does?
Is this a bug?

Thanks,

**Comment by AmandaRiu** [comment]
I'm having the same issue as well, except the image will actually zoom, but if I try to pan it, it immediately zooms the image back out.
