### ISSUE TITLE
Image shrinks on first touch

### ISSUE THREAD

**Issue by JensJensen** [chrisbanes/PhotoView#457]
When I do the first touch on the PhotoView (for example to zoom), the image automatically shrinks:
![Video](http://i.giphy.com/l0HlHfU6Np5ZjpgpG.gif)

I use the PhotoView widget as a child of a RelativeLayout in a fullscreen Activity. And it only happens on the first touch after starting the Activity. When I try to zoom a second time, everything works as expected.

**Comment by Jawnnypoo** [comment]
Can you reproduce this with one of the samples? I don't really see this happening in the samples.
