### ISSUE TITLE
Error If i put imageview in layout secound

### ISSUE THREAD

**Issue by esirahimian** [chrisbanes/PhotoView#458]
layout <<
  <ImageView

        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/s1"
        android:id="@+id/imageView2"
        android:layout_weight="1" />

and  main is << 
ImageView imageView;
        imageView=(ImageView)findViewById(R.id.imageView2);
        PhotoViewAttacher photoViewAttacher1=new PhotoViewAttacher(imageView);
then if i put imageview in layout secound program cant run its close
if i layout is main is worked not problem

**Comment by Jawnnypoo** [comment]
I am not sure what the issue is here and how it relates to this project. Please take a look at the samples in this repo for further help.
