### ISSUE TITLE
Can't add in android studio 2.2.3

### ISSUE THREAD

**Issue by thitoo** [chrisbanes/PhotoView#461]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

**Comment by Jawnnypoo** [comment]
You are most likely including a dependency that includes the files of PhotoView within it. Check your dependencies and make sure none of them have the same files as PhotoView in them. 

Otherwise it might be a MultiDex issue which you just need to ensure you are Multidexing properly
