### ISSUE TITLE
Images not loading in RecyclerView

### ISSUE THREAD

**Issue by tkshnwesper** [chrisbanes/PhotoView#463]
Hi, I had posted a [question](https://stackoverflow.com/questions/41315703/recycleview-list-items-not-appearing) earlier on SO regarding the same problem, and I thought that I had fixed it but that wasn't the case.

The good news is that, I am now sure as to what was causing it. The images load fine when I comment out `PhotoViewAttacher(t)` (line 108). The code of the concerned activity is [here](https://gist.github.com/tkshnwesper/13eade491dc3cc59710d2f1e429c8505) (you can test it if you like, it doesn't use any layout or resources).

**Comment by Jawnnypoo** [comment]
I don't think this is a problem with this library. There are a few things wrong with your code here, including the fact that you are loading the bitmaps synchronously on the main thread. You need to look more into the samples provided int this project on how to set up and use RecyclerView
