### ISSUE TITLE
How to check if PhotoViewAttacher is scaling?

### ISSUE THREAD

**Issue by zhenleiji** [chrisbanes/PhotoView#464]
I customised PhotoViewAttacher to support more gestures, that means I created a class that extends PhotoViewAttacher. My class overrides onTouch method and adds the new gesture "swipe to dismiss". But I need to know when PhotoViewAttacher is scaling in order to don't run this new gesture.

I didn't find any method that give me this information. And mScaleDragDetector is private 😢. So I can't access from my custom view the method  mScaleDragDetector.isScaling();

Can anybody help me?

Thanks in advance!

**Comment by vsay01** [comment]
I used onScaleChangeListener to detect if the image is scaling or not.

You can check the answer in this [closed PR.](https://github.com/chrisbanes/PhotoView/issues/574)
