### ISSUE TITLE
I find that photoview makes two repeated network requests to show a picture every time,is that normal?

### ISSUE THREAD

**Issue by xuyichao** [chrisbanes/PhotoView#468]

**Comment by xuyichao** [comment]
the gradle dependencies is 'com.github.chrisbanes:PhotoView:1.3.0'

**Comment by Jawnnypoo** [comment]
PhotoView does nothing to show a picture. It makes no attempts to load an image from the network whatsoever. You must be mistaking the calls coming from somewhere else.
