### ISSUE TITLE
photoview  + viewpager + picasso

### ISSUE THREAD

**Issue by randomlock** [chrisbanes/PhotoView#470]
There are 2 issue that I am facing when using viewpager with picasso library and photoview library.

1) Some of the images don't zoom, rather sometimes the next image is zoomed instead.

2) Sometimes when I zoom an image, then adjacent image is also zoomed along with the current one 

` 

    @Override
    public boolean isViewFromObject(View view, Object object) {
        return view == object;
    }

    @Override
    public Object instantiateItem(ViewGroup container, int position) {

        String imageUrl = images.get(position);
        final PhotoView imageView = new PhotoView(context);
        final PhotoViewAttacher mAttacher = new PhotoViewAttacher(imageView);
       
            Picasso.with(context).load(imageUrl).into(imageView, new Callback() {
                @Override
                public void onSuccess() {

                    if (mAttacher != null) {
                        mAttacher.update();
                    } 

                }

                @Override
                public void onError() {

                }
            });
        

        container.addView(imageView, ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);

        return imageView;
    }

    @Override
    public void onViewTap(View view, float v, float v1) {
        Toaster.make(context,"hello");
        ((ImageViewPagerActivity) context).animateToolbar();
    }`

**Comment by 1hsyn1** [comment]
when I do it galaxy s6 edge there is no problem. But I have an android one project phone which has the latest version of android. The problems described above are exist on the android one phone.

**Comment by Jawnnypoo** [comment]
Try it without the attacher. I don't think you actually need to worry about the attacher at all in this case
