### ISSUE TITLE
Error PhotoView Force closed

### ISSUE THREAD

**Issue by esirahimian** [chrisbanes/PhotoView#472]
i have problem
its worked but only  imageview must in activity_main.xml 
if i created image view in activity_main2.xml  apk run is closed app
and have problem
pls help thanks
`   ImageView mImageView;
PhotoViewAttacher mAttacher;

@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    // Any implementation of ImageView can be used!
    mImageView = (ImageView) findViewById(R.id.iv_photo);

    // Set the Drawable displayed
    Drawable bitmap = getResources().getDrawable(R.drawable.wallpaper);
    mImageView.setImageDrawable(bitmap);

    // Attach a PhotoViewAttacher, which takes care of all of the zooming functionality.
    mAttacher = new PhotoViewAttacher(mImageView);
}`

**Comment by Jawnnypoo** [comment]
If you can give a stack trace and more of an indication that this library is causing the crash, I can reopen this.
