### ISSUE TITLE
problem with glide , picture not showing 

### ISSUE THREAD

**Issue by kalinkon** [chrisbanes/PhotoView#475]
public class ImageViewActivity extends AppCompatActivity {

    String mImage;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mImage=getIntent().getStringExtra("image");

        requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);
        setContentView(R.layout.image_viewer);

        final ImageView imageView =(ImageView)findViewById(R.id.imageView);
        Glide.with(this).load(mImage).into(imageView);

        PhotoViewAttacher picView = new PhotoViewAttacher(imageView);

        picView.update();

//        final Animation zoomAnimation = AnimationUtils.loadAnimation(this, R.anim.zoom);
//        imageView.startAnimation(zoomAnimation);
    }

``
}

**Comment by salways1994** [comment]
just use the PhotoView instead of the ImageView in xml

**Comment by Jawnnypoo** [comment]
It is probably not related to this library, I will reopen the issue if you can prove that the library is causing this.

**Comment by kalinkon** [comment]
hey John,
it's working after using photoview.
Thabks a lot :)
