### ISSUE TITLE
Inefficient API is used

### ISSUE THREAD

**Issue by struggggle** [chrisbanes/PhotoView#478]
Dear developers,

I found two inefficient API, setImageResource() and setImageURI(), are used in PhotoView.

For setImageResource() and and setImageURI(), Google says this:
https://developer.android.com/reference/android/widget/ImageView.html#setImageResource(int)
https://developer.android.com/reference/android/widget/ImageView.html#setImageURI(android.net.Uri)
" This does Bitmap reading and decoding on the UI thread, which can cause a latency hiccup. If that's a concern, consider using setImageDrawable(android.graphics.drawable.Drawable) or setImageBitmap(android.graphics.Bitmap) and BitmapFactory instead. "

I noticed that in the following code, setImageResource() and setImageURI() are used:

https://github.com/chrisbanes/PhotoView/blob/master/library/src/main/java/uk/co/senab/photoview/PhotoView.java#L159
https://github.com/chrisbanes/PhotoView/blob/master/library/src/main/java/uk/co/senab/photoview/PhotoView.java#L167
https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/uk/co/senab/photoview/sample/RotationSampleActivity.java#L36  (the image size is 92.4KB, 1024*640)

https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/uk/co/senab/photoview/sample/ViewPagerActivity.java#L53

Do you think the use of setImageResource() and setImageURI() will affect PhotoView's performance? If so, maybe we should replace it with setImageDrawable() or setImageBitmap().

Thanks.

**Comment by Jawnnypoo** [comment]
It is up to the end developer on if they used setImageUri or not. We have an example with Picasso which would be the preferred method of loading an image off of the UI thread. setImageResource is fine to use with no drawbacks. It would essentially be the same as loading the drawable and using setImageDrawable.
