### ISSUE TITLE
PhotoViewAttacher not removed from ViewTreeObserver after calling cleanup

### ISSUE THREAD

**Issue by Goomba** [chrisbanes/PhotoView#479]
The problem is that removeGlobalOnLayoutListener(this) is called only when the reference to the imageView is not null. 

This can be a problem because the reference to the PhotoViewAttacher will never be removed from the ViewTreeObserver. This is a severe issue, since they can accumulate indefinitely on RAM.

The fix is quite simple: in the PhotoViewAttacher keep a WeakReference to the ViewTreeObserver, and in the cleanup method call removeGlobalOnLayoutListener on it if the imageView is null.

**Comment by Jawnnypoo** [comment]
This should not be an issue anymore since the global listener is no longer needed.
