### ISSUE TITLE
ScaleType not getting set properly if set in XML

### ISSUE THREAD

**Issue by Raenar4k** [chrisbanes/PhotoView#484]
Hey. I've just updated and encountered this problem where scaleType set in xml stopped working after update.
vesion `1.3.1`:
```xml
    <uk.co.senab.photoview.PhotoView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"
        android:src="@drawable/sample_map"/>
```
Image loads like this at max zoom out : 
![1](https://cloud.githubusercontent.com/assets/13849790/24099449/fc21ee4e-0d77-11e7-9336-b0e6c308b0db.png)

vesion `2.0.0`:
```xml
    <com.github.chrisbanes.photoview.PhotoView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:scaleType="centerCrop"
        android:src="@drawable/sample_map"/>
```
Image loads like this at max zoom out : 
![2](https://cloud.githubusercontent.com/assets/13849790/24099457/0d7ca5a8-0d78-11e7-8e5b-b2eb2871f629.png)

Is this an intended change? Or maybe im missing something?
Thanks!

**Comment by Jawnnypoo** [comment]
Can you try setting the scale type in code? I think the issue might be with the scale type being set in XML. Can you verify this?

**Comment by Raenar4k** [comment]
@Jawnnypoo Sorry it took me that long.
Yep, can confirm - works if scale type is set in code.

**Comment by Jawnnypoo** [comment]
Thanks for confirming, there will be a fix for this in the next version!

**Comment by Raenar4k** [comment]
Awesome! Thanks for working on this lib :)
