### ISSUE TITLE
when working with ViewPager,  memory is rising。。

### ISSUE THREAD

**Issue by lizixian18** [chrisbanes/PhotoView#489]
when working with ViewPager and Glide,  memory is rising。。
![image](https://cloud.githubusercontent.com/assets/16240767/24484516/300cda14-1531-11e7-9d5a-0f26d0666f96.png)

**Comment by Jawnnypoo** [comment]
If this is an inner class, you should make the inner class static. If you still have the issue then, can you attempt to narrow down what you think might be this library causing the issue? We have a sample with a ViewPager, and it does not seem to have memory issues

**Comment by lizixian18** [comment]
my code reference this sample with a ViewPager,the difference is that my adapter is not using static.

**Comment by Jawnnypoo** [comment]
Can you confirm that when your view is an ImageView, the memory does not rise, but when it is a PhotoView it does?

**Comment by Jawnnypoo** [comment]
If you can provide more info and proof that this is with this library, I will reopen
