### ISSUE TITLE
build time occur issue

### ISSUE THREAD

**Issue by PratikPagada** [chrisbanes/PhotoView#492]
**Redmi note3 working well , Samsung j2 not build.** 

Error:Execution failed for task ':app:transformClassesWithJarMergingForNewliveDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: uk/co/senab/photoview/PhotoViewAttacher$1.class

**Comment by Jawnnypoo** [comment]
This is a sign that another library you are using has added PhotoView to their classpath manually. You can either figure out which library has done this, or update to 2.0.0 where this should not be an issue, since the classpath changed
