### ISSUE TITLE
HackyViewPager is still necessary?

### ISSUE THREAD

**Issue by hkurokawa** [chrisbanes/PhotoView#500]
I am trying to use this library and just curious if I still need HackyViewPager to use PhotoView in ViewPager.

The comment of HackyViewPager indicates the workaround is for issue #4 which is already closed now.
https://github.com/chrisbanes/PhotoView/blob/master/sample/src/main/java/com/github/chrisbanes/photoview/sample/HackyViewPager.java#L9

So I guess this workaround is no more necessary in  the latest release but it seems still people are using HackyViewPager (https://github.com/chrisbanes/PhotoView/issues/206). So I have to use HackyViewPager if I want to use the latest PhotoView in a ViewPager?

Thank you for your support in advance.

**Comment by Jawnnypoo** [comment]
Yep, its still needed since it is still not fixed in the framework 😢

**Comment by hkurokawa** [comment]
Thank you for your response. I will go with the hack :wink:
