### ISSUE TITLE
How to save state of image

### ISSUE THREAD

**Issue by nithinpmolethu** [chrisbanes/PhotoView#505]
i just want to save the current state of image in photoview.
when i change the zoom and apply some effects to it then the current state of image restore back to original state and i lose my zoomed state.
i want to keep my current zoomed state and apply effects.
is there any way to lock the panning and translation at the time i want and activate it again when i need

**Comment by vvit** [comment]
Try this:
```
        Matrix matrix = new Matrix();
        mPhotoView.getAttacher().getSuppMatrix(matrix);
        mPhotoView.setImageBitmap(filteredBitmap);
        mPhotoView.getAttacher().setDisplayMatrix(matrix);
```

**Comment by nithinpmolethu** [comment]
getAttacher()
thers nothing like that!!

**Comment by vvit** [comment]
Are you sure?

**Comment by nithinpmolethu** [comment]
am new to this so i might not understand well
it say no such method when i call photoview.getAttacher.

**Comment by vvit** [comment]
You should check the `master` branch. There is.

**Comment by nithinpmolethu** [comment]
Filter myFilter = new Filter();
        Point[] rgbKnots;
        rgbKnots = new Point[3];
        rgbKnots[0] = new Point(0, 0);
        rgbKnots[1] = new Point(161, 86);
        rgbKnots[2] = new Point(255, 255);

        myFilter.addSubFilter(new ToneCurveSubfilter(rgbKnots, null, null, null));
        Bitmap outputImage = myFilter.processFilter(gallerytxt);

        Matrix matrix = new Matrix();
        mPhotoView.getAttacher().getSuppMatrix(matrix);
        mPhotoView.setImageBitmap(outputImage );
        mPhotoView.getAttacher().setDisplayMatrix(matrix);

but i cant resolve getAttacher

**Comment by vvit** [comment]
Do you see the method?
https://github.com/chrisbanes/PhotoView/blob/master/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoView.java#L69-L71

**Comment by nithinpmolethu** [comment]
no its not present in my library

**Comment by nithinpmolethu** [comment]
Matrix matrix = new Matrix();
        p1.getDisplayMatrix(matrix);
        p1.setImageBitmap(outputImage );
        p1.setDisplayMatrix(matrix);

is this same as you written

**Comment by vvit** [comment]
Since it calls different functions - no it's not the same 😝
I won't able to help you.

**Comment by Jawnnypoo** [comment]
@nithinpmolethu Not present in your library? Sounds like you have pulled in the code from PhotoView and are using it for some custom library? If so, this is beyond the scope of this library. Feel free to continue to chat with @vvit about this issue if he is willing to help out, but I am closing this since it is not an actual issue with PhotoView.
