### ISSUE TITLE
Why Can't use it

### ISSUE THREAD

**Issue by sunshaobei** [chrisbanes/PhotoView#506]
when i write it to grade,it show error

**Comment by happycowsarecool** [comment]
I'm having the same problem. It says
Failed to resolve com.github.chrisbanes:PhotoView:latest.release.here

**Comment by Jawnnypoo** [comment]
You need to replace latest.release.here with the latest release: 2.0.0 right now

**Comment by heming0512** [comment]
actually  is:
compile 'com.github.chrisbanes:PhotoView:2.0.0'

**Comment by ravirupareliya** [comment]
You might have forgot to write 

    maven { url "https://jitpack.io" }

in your root level `build.gradle`

**Comment by sajjadiq95** [comment]
same problem here i replaced  "latest.release.here" with the latest release: 2.0.0 and I added 
maven { url "https://jitpack.io" } to build.gradle and it's still not working idk why

**Comment by MohammadHammoud** [comment]
use
  implementation 'com.github.chrisbanes:PhotoView:2.3.0'
and add these two in build.gradle of your project
maven { url "https://jitpack.io" }
maven { url "https://maven.google.com" }
