### ISSUE TITLE
new PhotoViewAttacher(imageView) not working

### ISSUE THREAD

**Issue by kjf3006** [chrisbanes/PhotoView#508]
I used this dependency until now with no Problems: `'com.commit451:PhotoView:1.2.5'`
Now i tried to move to the new library: `'com.github.chrisbanes:PhotoView:2.0.0'`

The problem is, now all images are completely zoomed in, touch gestures are not working. I am using a subclass of ImageView, so using the standart PhotoView is no option. Here's the layout and my code:

```
<CustomImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/imageView"
        android:scaleType="centerCrop"
        android:layout_centerVertical="true" />
```

```
CustomImageView imageView = (CustomImageView) rootView.findViewById(R.id.imageView);
....
new PhotoViewAttacher(imageView);
```

**Comment by SuperThomasLab** [comment]
I think it has to do with `android:scaleType="centerCrop"`. For me it worked after changing the value to `matrix`.

**Comment by kjf3006** [comment]
Thanks now I's working!
