### ISSUE TITLE
Mantain scale and visible area

### ISSUE THREAD

**Issue by josemssilva** [chrisbanes/PhotoView#509]
Can't seem to find a way to keep scale AND visible area when changing images. Everytime I change image, and scale, it gets centered. Is there a way to translate it?

**Comment by kiwox** [comment]
I need the same, looking for it.

**Comment by huyduongtu** [comment]
I'm looking the solution for it, too

**Comment by evil123** [comment]
hello

**Comment by evil123** [comment]
I hava a problem!
