### ISSUE TITLE
Image wont zoom or pan!

### ISSUE THREAD

**Issue by Muddz** [chrisbanes/PhotoView#510]
I can't get the code to zoom or do anything when I load an Image from the gallery via `Intent`.

I have this simple code:
      

>   imageView1.getAttacher().setZoomable(true); 
>         imageView1.getAttacher().setScaleType(ImageView.ScaleType.FIT_CENTER);

    <LinearLayout
        android:id="@+id/layouter2x2"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_above="@id/bottomBar"
        android:layout_below="@id/toolbar"
        android:orientation="horizontal">

        <com.github.chrisbanes.photoview.PhotoView
            android:id="@+id/imageView1"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginRight="0.5dp"
            android:layout_weight="1"
            android:background="#747474" />

        <com.github.chrisbanes.photoview.PhotoView
            android:id="@+id/imageView2"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_weight="1"
            android:background="#747474" />
    </LinearLayout>

**Comment by Jawnnypoo** [comment]
Set your width on each PhotoView to `0dp` instead of `match_parent`

**Comment by Muddz** [comment]
@Jawnnypoo I solved the problem. It was because I had a onTouchListener on my imageView that must have blocked `PhotoView`'s functionality

**Comment by Jawnnypoo** [comment]
Great!
