### ISSUE TITLE
[Request] Update the sample app on Google Play

### ISSUE THREAD

**Issue by ParkerK** [chrisbanes/PhotoView#518]
Just noticed that the sample app on the play store hasn't been updated since 2012 - the current one has a lot more activities, so would it be possible to update it?

https://play.google.com/store/apps/details?id=uk.co.senab.photoview.sample

**Comment by Jawnnypoo** [comment]
This won't be fixed, the Play Store listing is controlled by Chris who is no longer maintaining this library
