### ISSUE TITLE
app crashes if you zoom out quickly

### ISSUE THREAD

**Issue by gateco** [chrisbanes/PhotoView#519]
i put the PhotoView on a ViewPager ,
sometimes when i zoom back quickly app crashes 

FATAL EXCEPTION: main
Process: com.example.app, PID: 4862
java.lang.IllegalArgumentException: pointerIndex out of range
at android.view.MotionEvent.nativeGetAxisValue(Native Method)
at android.view.MotionEvent.getX(MotionEvent.java:2381)

**Comment by Jawnnypoo** [comment]
https://github.com/chrisbanes/PhotoView#issues-with-viewgroups
