### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by lh414035210** [chrisbanes/PhotoView#527]
![k62n6ul ae 6aktx 8_3](https://user-images.githubusercontent.com/24253339/28358693-5383b92c-6ca2-11e7-8762-2d8d79250579.png)

**Comment by vilius-valiusis** [comment]
com.github.chrisbanes:PhotoView:**latest.release.here** with the latest version 2.1.2, something like this compile 'com.github.chrisbanes:PhotoView:2.1.2'. 
Also, make sure you added JitPack repository like this.
![image](https://user-images.githubusercontent.com/22169342/28359201-5cc01884-6c69-11e7-8aa6-8f04bd345b63.png)

**Comment by lh414035210** [comment]
![ghp a2 j up3 t hsy 67ey](https://user-images.githubusercontent.com/24253339/28359702-b6a3dd04-6ca5-11e7-8137-3e07bdf5cade.png)

**Comment by lh414035210** [comment]
![ghp a2 j up3 t hsy 67ey](https://user-images.githubusercontent.com/24253339/28359719-c7bdd630-6ca5-11e7-9429-01703f489d94.png)

**Comment by vilius-valiusis** [comment]
Wrong gradle file. There are two Project and Module 
![image](https://user-images.githubusercontent.com/22169342/28359999-03607fe2-6c6c-11e7-8964-0d1aaa1d9cf4.png).
Go to the Module gradle file and add in there like this:
![image](https://user-images.githubusercontent.com/22169342/28360045-336fdb92-6c6c-11e7-9849-6f9d287eebbe.png)

**Comment by lh414035210** [comment]
Thank you, foreign friends. My problem has been solved
