### ISSUE TITLE
how to set initial zoom level programatically?

### ISSUE THREAD

**Issue by shivam21** [chrisbanes/PhotoView#531]

**Comment by LolWalid** [comment]
You can use ```setScale(Float scale)``` method.

Be sure that the scale value is within the range of ```minScale``` and ```maxScale``` or an exception will be raised.

**Comment by hanswimtj** [comment]
Have you solved your issue? I use setScale(float scale) method at initialization, but it doesn't work, unless I post setScale(float scale) with a long delay.
