### ISSUE TITLE
With Glide the img always LEFT|TOP ,NOT center in screen

### ISSUE THREAD

**Issue by heiyeliuying** [chrisbanes/PhotoView#532]
when i use Glide to async load my images .the image always align to left|top ,when i touch and more the screen ,it will become center. 

This is my code .(inner ViewPager)

` var photoView:PhotoView = contentView.findViewById(R.id.photo_view)
            photoView.scaleType = ImageView.ScaleType.FIT_CENTER
            photoView.maximumScale = 2f
            photoView.minimumScale = 0.3f
            var attacher = PhotoViewAttacher(photoView)
//            Glide.with(mContext).load(imgsList[position]).into(photoView)
//            attacher.update()

            Glide.with(mContext).load(imgsList[position])
                    .override(SimpleTarget.SIZE_ORIGINAL, SimpleTarget.SIZE_ORIGINAL)
                    .dontAnimate()
                    .into(object : SimpleTarget<GlideDrawable>() {
                        override fun onResourceReady(resource: GlideDrawable?, glideAnimation: GlideAnimation<in GlideDrawable>?) {
                            photoView.setImageDrawable(resource!!)
                            attacher.update()
                        }
                        override fun onStop() {
                            super.onStop()
                        }
                    })`

**Comment by heiyeliuying** [comment]
new version is ok. I just update my version of photoview

**Comment by George-Soros** [comment]
@heiyeliuying 我有同样的问题，你的版本是多少，可以贴一下吗？
