### ISSUE TITLE
Support dataBinding in library

### ISSUE THREAD

**Issue by jpage4500** [chrisbanes/PhotoView#539]
I've been converting my xml layouts over to use data binding (I was using Butterknife but data binding is a great improvement IMO)

Anyway, I *think* that every library you use in the xml layout must also have dataBinding.enabled = true in it's build.gradle property file. Is that something you can add to this library?

At least when I try to use PhotoView in my xml I'm getting this compile error:
```
.../databinding/ActivityTicketingEventBinding.java
Error:(37, 49) error: cannot find symbol class PhotoView
```

I also had the same error in one of my own external libraries which started working again once I added the databinding line below to my library's build.gradle file

```
android {
    compileSdkVersion global_compileSdkVersion
    buildToolsVersion global_buildToolsVersion
    dataBinding.enabled = true
```

**Comment by Jawnnypoo** [comment]
I think your issue is unrelated to the library not enabling databinding, it would be impractical if every custom view library had to enable data binding for it to work
