### ISSUE TITLE
Failed to resolve: com.github.chrisbanes:PhotoView:2.1.3

### ISSUE THREAD

**Issue by kassymbekoff** [chrisbanes/PhotoView#543]
Hello! I can't download library with gradle.
compile 'com.github.chrisbanes:PhotoView:2.1.3'
Error: Failed to resolve: com.github.chrisbanes:PhotoView:2.1.3

**Comment by iNoles** [comment]
Looks like you forget about 

allprojects {
	repositories {
        maven { url "https://jitpack.io" }
    }
}

**Comment by kassymbekoff** [comment]
Yeap, solved, thank you!
