### ISSUE TITLE
Image stands still when zooming

### ISSUE THREAD

**Issue by keeblebogdan** [chrisbanes/PhotoView#546]
Updated from 1.2 to 2.0.0 and the following behaviour occurs: [https://streamable.com/b8vxj](url)
I zoom in on the imageview, I'm logging the scale value and I see that is changing and the zoom is fine, but the image stands still. 

Would greatly appreciate some help as I can't seem to figure it out after 2 days. Thank you.

**Comment by divysoni3** [comment]
I have the same problem, How did you resolve this?

**Comment by divysoni3** [comment]
got the solution [here](https://github.com/chrisbanes/PhotoView/issues/495)

**Comment by keeblebogdan** [comment]
If i remember correctly, i changed the  public void **onMatrixChanged**(RectF rect) function.

Version 1.2: mAttacher.getDisplayMatrix(displayMatrix);
Version 2.0.0:             Matrix displayMatrix = new Matrix();     mAttacher.getSuppMatrix(displayMatrix);

Plus my TaggableImageView had scaleType="fitXY" in previous version. Now scaleType="matrix".
Hope this helps you.

**Comment by divysoni3** [comment]
@keeblebogdan thanks for your quick response. I just changed imageView scale type and my problem solved:
`imageView.setScaleType(ImageView.ScaleType.MATRIX);`

**Comment by cse-msn** [comment]
@divysoni3  - Thank you. Your solution worked for me. :) 👍
