### ISSUE TITLE
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/github/lzyzsd/jsbridge/CallBackFunction.class

### ISSUE THREAD

**Issue by NovakovskiyVadim** [chrisbanes/PhotoView#559]
I use com.github.chrisbanes:PhotoView:2.1.3 and have this error. How do I fix it?

**Comment by NovakovskiyVadim** [comment]
I use com.github.chrisbanes:PhotoView:2.1.3 and have this error. How do I fix it?

**Comment by Jawnnypoo** [comment]
Looks like the com.github.lzyzsd.jsbridge library might be using the same code in its classpath as is in this library. Or there is an issue with Multidex.
