### ISSUE TITLE
App crash when zoom in/ zoom out multiple times

### ISSUE THREAD

**Issue by tabassumLatif** [chrisbanes/PhotoView#566]
App gets  crash when we do zoom in/ zoom out frequently (with speed) 
Error: pointerIndex out of range.

**Comment by tipa** [comment]
experiencing the same problem

**Comment by gaolingxiao** [comment]
Just catch the exception in your onInterceptTouchEvent function

**Comment by Jawnnypoo** [comment]
Its in the readme
