### ISSUE TITLE
Could not resolve com.github.chrisbanes:PhotoView:2.1.3

### ISSUE THREAD

**Issue by sika78** [chrisbanes/PhotoView#567]
Hi all,

I've went over the documentation.
I added this to the gradle files:
  maven {
            url "https://jitpack.io"
        }

then this >> compile 'com.github.chrisbanes:PhotoView:2.1.3'

I get this error:

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.github.chrisbanes:PhotoView:2.1.3.
  Required by:
      project :app
   > Could not resolve com.github.chrisbanes:PhotoView:2.1.3.
      > Could not get resource 'https://jitpack.io/com/github/chrisbanes/PhotoView/2.1.3/PhotoView-2.1.3.pom'.
         > Could not GET 'https://jitpack.io/com/github/chrisbanes/PhotoView/2.1.3/PhotoView-2.1.3.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Any thoughts?

Thanks!

**Comment by Jawnnypoo** [comment]
Looks like something with the security of your network being weird. Try it out on a different network

**Comment by qi19901212** [comment]
hi  brother  ?is it work ?
