### ISSUE TITLE
引用报错

### ISSUE THREAD

**Issue by Danielandroid** [chrisbanes/PhotoView#572]
Unable to resolve dependency for ':photoview_test@debugUnitTest/compileClasspath': Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.

Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.
Versions that do not match:
    2.1.3
    2.1.2
    2.1.1
    2.1.0
    2.0.0
    + 6 more
Required by:
    project :photoview_test

**Comment by yangshiliang** [comment]
Change 'com.github.chrisbanes:PhotoView:latest.release.here' to 'com.github.chrisbanes:PhotoView:2.1.3'

**Comment by Danielandroid** [comment]
thank you
