### ISSUE TITLE
Bug with multi fingers touch still present?

### ISSUE THREAD

**Issue by jffluis** [chrisbanes/PhotoView#581]
Just using your lib 6 months from now and only today I realised that when you touch randomly with many fingers the app crashes and raises this exception: 

`java.lang.IllegalArgumentException: pointerIndex out of range`

Can you help me fixing this issue?

**Comment by iNoles** [comment]
Go to https://github.com/chrisbanes/PhotoView/blob/master/README.md, Read the section that said Issue with ViewGroup

**Comment by Jawnnypoo** [comment]
Yep, that's the solution in the README there
