### ISSUE TITLE
Is there a way to restore focus point?

### ISSUE THREAD

**Issue by siralam** [chrisbanes/PhotoView#589]
I noticed that if I reload image into `PhotoView` (e.g. Using Glide),  
The zoom level and the focus point will be reset.  

I understand this may be the intended behavior of the library.  
I can also restore the zoom level by using `getScale()` and `setScale()`.

But I cannot find similar method regarding the focus point. I had a brief look into the source code, it seems there is no such exposed API.

I am willing to modify the code by myself; but I am not sure how to do it; it looks like the focus point is controlled by `mSuppMatrix`. But I also noticed `mBaseMatrix` and `mDrawMatrix`, and a couple of variables that I do not understand.  

Would you mind giving me a hand on it? I may submit a pull request if I managed to add this API.

**Comment by siralam** [comment]
Just found that I instead of `getScale()` and `setScale()`, I can use `getSuppMatrix()` and `setSuppMatrix()`. This suppMatrix probably stored both zoom level and focus point information as it worked out perfectly after a quick try.

Just create a new empty Matrix to pass it as a parameter to `getSuppMatrix()`.
`Matrix zoomLevelStore = new Matrix();`

Hope this will help someone else in the future.

**Comment by marcshilling** [comment]
Helped me for sure, thanks!
