### ISSUE TITLE
Gradle Issues 

### ISSUE THREAD

**Issue by jaymin2609** [chrisbanes/PhotoView#610]
implementation 'com.github.chrisbanes:PhotoView:1.3.0'

Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Luk/co/senab/photoview/gestures/OnGestureListener;

**Comment by Jawnnypoo** [comment]
Looks like another library you are using is including duplicate code from this library, or you need to setup multidex.
