### ISSUE TITLE
Failed to resolve: com.github.chrisbanes.photoview:library:2.0.0

### ISSUE THREAD

**Issue by zhangzhen92** [chrisbanes/PhotoView#616]
When I use it at Android studio ,I have Add "maven { url "https://jitpack.io" } " in root build.gradle file ,and dependencies {
    implementation 'com.github.chrisbanes:PhotoView:2.0.0'
}... but Failed to resolve: com.github.chrisbanes.photoview:library:2.0.0

**Comment by tmac1999** [comment]
can you post your build.gradle file content

**Comment by Jawnnypoo** [comment]
Try it with 2.1.4

**Comment by jasonpp** [comment]
I guess your remote repository must have some error . I got the same issues with the guy show up . I use the `implementation 'com.github.chrisbanes:PhotoView:2.1.4`. It's no problem.

**Comment by chhatrasal09** [comment]
I am also facing this issue.

**Comment by ujjwalagrawal17** [comment]
I am also facing this issue. Can we re-open this issue @Jawnnypoo ?

**Comment by NickIvantsov** [comment]
+1

**Comment by Jawnnypoo** [comment]
If you are seeing issues, it is more than likely an issue with Jitpack or your internet connection.

**Comment by liushengxin** [comment]
> ERROR: Failed to resolve: com.github.chrisbahines:PhotoView:2.00

I meet same problem and i have add  add "maven { url "https://jitpack.io" } " in root build.gradle

**Comment by EmedStoreIT** [comment]
> 
> 
> If you are seeing issues, it is more than likely an issue with Jitpack or your internet connection.

Thanks
Adding **maven { url "https://jitpack.io" }** in project level build.gradle resolved my issue.

**Comment by RumsPatel** [comment]
> 
> 
> If you are seeing issues, it is more than likely an issue with Jitpack or your internet connection.

Thanks
Adding maven { url "https://jitpack.io" } in project level build.gradle resolved my issue.

**Comment by UsamaElgendy** [comment]
it's solved the problem thx 👍 @RumsPatel

**Comment by SIMMORSAL** [comment]
the problem for me was that I had put`maven { url "https://jitpack.io" }` in the wrong place.

I'd put it inside __buildscript__ -> __repositories__ (mistakenly next to `maven { url 'https://maven.fabric.io/public' }`, but it should've been inside __allprojects__ -> __repositories__

**Comment by rayzone107** [comment]
I was also facing the same issue, but my problem was that I'd not included `maven { url "https://jitpack.io" }` in the allprojects -> repositories inside the project level gradle file.

```
buildscript {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```
I had it added above, and the library failed to load.
Once I added it to the below code also, it worked:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

Hope this helps.

**Comment by iliyasansari07** [comment]
Paste - _**maven { url "https://www.jitpack.io" }**_ in settings.gradle and 
paste this dependency - _**implementation 'com.github.chrisbanes:PhotoView:latest.release.here'**_ in build.gradle

**Comment by IssamAth** [comment]
i already have this inside my Project Gradle 
```
repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
```
I have also added  ```  implementation 'com.github.chrisbanes:PhotoView:2.3.0' ``` to the dependencies inside Module Gradle yet it's still not working, can anyone help me ?

**Comment by Sartharian** [comment]
> i already have this inside my Project Gradle
> 
> ```
> repositories {
>         google()
>         mavenCentral()
>         maven { url 'https://jitpack.io' }
>     }
> ```
> 
> I have also added ` implementation 'com.github.chrisbanes:PhotoView:2.3.0'` to the dependencies inside Module Gradle yet it's still not working, can anyone help me ?

Forget all above. Due to new update, make sure to do [this steps](https://stackoverflow.com/a/70989593) (the Shridhar Chouksey's answer) before implement this project. 

Good luck!
