### ISSUE TITLE
gradle report exceptions

### ISSUE THREAD

**Issue by huma8848888** [chrisbanes/PhotoView#623]
I have established a all new android project using androidAPI 23,and followed the steps wirten in Readme.md,but when i click sync the gradle in android studio it reports exceptions,the following is what gradle presents:
Unable to resolve dependency for ':app@debug/compileClasspath': Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not find any version that matches com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

**Comment by Jawnnypoo** [comment]
Change latest.release.here to 2.1.3
