### ISSUE TITLE
How to set initial zoom with setScale

### ISSUE THREAD

**Issue by tronious** [chrisbanes/PhotoView#627]
Saw a number of issues entered for this.  This is not an issue...rather a solution to a seemingly common question.

If you are trying to set the initial scaling factor of your image using 'setScale', it appears that it will not work until view renders.

To set the initial zoom factor do the following (works for me):

if this is not working for you try setting the scale AFTER the view renders:

        dashboard_image = (PhotoView) TheView.findViewById(R.id.dashboard_image);

        ViewTreeObserver vto = dashboard_image.getViewTreeObserver();
        vto.addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                dashboard_image.getViewTreeObserver().removeOnGlobalLayoutListener(this);

                dashboard_image.setScale(2f);
            }
        });

**Comment by Scorpikk** [comment]
@tronious, try to use this:
```java
dashboard_image.post(
        new Runnable() {
            @Override
            public void run() {
                dashboard_image.setScale(2f);
            }
        });
```

**Comment by Jawnnypoo** [comment]
@tronious 's solution is the better one, as it assures the view has had its layout call completed once. Posting in a runnable has a good chance that the view has had layout called, but it is not guaranteed.

**Comment by VitBr** [comment]
@tronious 's solution in kotlin
```kotlin
with(dashboard_image) {
    val run = Runnable { scale = 2f }
    post(run)
}
```
