### ISSUE TITLE
Failed to resolve com.github.chrisbanes:PhotoView:latest.release.here.

### ISSUE THREAD

**Issue by gptshubham595** [chrisbanes/PhotoView#660]
Even after adding Jitpack.io
And the file dependency then also it says failed to resolve except this I am able to resolve any other dependency

**Comment by Jawnnypoo** [comment]
Change `latest.release.here` to the version number in the badge in the README

**Comment by gptshubham595** [comment]
I have also written, 2.2.0 instead of that

**Comment by gptshubham595** [comment]
Then also not working

**Comment by Jawnnypoo** [comment]
Did you also add the jitpack url as it says in the README?

**Comment by gptshubham595** [comment]
Yes even after that
