### ISSUE TITLE
Failed to resolve: com.github.chrisbanes.photoview.PhotoView:2.2.0

### ISSUE THREAD

**Issue by niallwatchorn** [chrisbanes/PhotoView#664]
Unable to build. Have added the maven reference too.

**Comment by Jawnnypoo** [comment]
Did you add the JitPack url?

**Comment by niallwatchorn** [comment]
Yeah, removing the first photoview fixed it. Should probably update the readme. I had to use implementation 'com.github.chrisbanes:PhotoView:2.0.0'

**Comment by Jawnnypoo** [comment]
Where are you seeing the other one in the README? It appears correctly in the README for me
