### ISSUE TITLE
implementation 'com.github.chrisbanes:PhotoView:latest.release.here'  is wrong？

### ISSUE THREAD

**Issue by jackerjin** [chrisbanes/PhotoView#672]

**Comment by xd720p** [comment]
You have to replace latest.release.here with latest release number from badge. For example
`implementation 'com.github.chrisbanes:PhotoView:2.3.0'`. Also don't forget to add maven repo as it's said in README. 

Besides, you could just look through repo issues and find the same as yours.

**Comment by alcarazolabs** [comment]
I got stuck, I forget put the current version.
