### ISSUE TITLE
why? in  Jenkins  

### ISSUE THREAD

**Issue by qi19901212** [chrisbanes/PhotoView#686]
* What went wrong:
Could not resolve all files for configuration ':app:internalReleaseCompileClasspath'.
> Could not resolve com.github.chrisbanes:PhotoView:2.0.0.
  Required by:
      project :app
   > Could not resolve com.github.chrisbanes:PhotoView:2.0.0.
      > Could not get resource 'https://jitpack.io/com/github/chrisbanes/PhotoView/2.0.0/PhotoView-2.0.0.pom'.
         > Could not GET 'https://jitpack.io/com/github/chrisbanes/PhotoView/2.0.0/PhotoView-2.0.0.pom'.
            > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by Jawnnypoo** [comment]
This seems like something local with your network or your Jenkins configuration

**Comment by qi19901212** [comment]
no  network !  I change gradle 4.6    PhotoView:1.2.6.  is work .
