### ISSUE TITLE
加上依赖后一直在报错

### ISSUE THREAD

**Issue by ILoveChina1994** [chrisbanes/PhotoView#689]
依赖版本 implementation 'com.github.chrisbanes:PhotoView:2.0.0'
报的错误是：
Compilation failed; see the compiler error output for details.
我使用的是android studio 3.2.0的版本，
依赖版本 implementation 'com.github.chrisbanes:PhotoView:latest.release.here'
一堆错误Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.chrisbanes:PhotoView:latest.release.here.
Open File
Show Details

**Comment by Gamezpedia** [comment]
implementation 'com.github.chrisbanes:PhotoView:2.3.0'

**Comment by ILoveChina1994** [comment]
compile 'com.github.chrisbanes.photoview:library:+'，后来找到了这个版本，2.3.0这个版本试过，也是报错，这个PhotoView有没有办法改变它的最大和最小缩放尺寸，原有的放大的尺寸太小，

**Comment by moonlight2012** [comment]
我也是这个问题，上一个项目2.0.0正常使用。
新项目，无论是2.0.0 还是2.3.0 都是提示出错。

先用上 ‘com.github.chrisbanes.photoview:library:+’
