### ISSUE TITLE
ViewPager and PhotoView swiping issue

### ISSUE THREAD

**Issue by jessloran** [chrisbanes/PhotoView#704]
Hello, I am developing a gallery app and I want to add the sliding gallery option where a user can open a gallery swipes left / right to navigate between the images. I am using a ViewPager/PagerAdapter to display the images and it works without issues.

I have decided to try PhotoView to allow zooming and it works with my project. Though, it is not smooth enough. When I swipe left or right sometimes the swipe does not get carried out and I have to swipe again to do it. On that unsuccessful swipe I see 20% of the next slide then the pager goes back to the current slide. In other words, the swipe causes 20% of the next slide to appear and then I am back on the current slide.

The issue is only available when I use the PhotoView. I have tried the hacky solution. That did not help. Is there any way to combat this issue?

**Comment by jessloran** [comment]
I have went with a different library that does not have this issue.

**Comment by JunWeiAndroid** [comment]
> I have went with a different library that does not have this issue.

which library, ths

**Comment by jessloran** [comment]
@JunWeiAndroid, TouchImageView.
