### ISSUE TITLE
How can I get Action_UP when i drag the photo slowly?

### ISSUE THREAD

**Issue by luckysmg** [chrisbanes/PhotoView#729]
I found that when I drag photo fast ,I can receive an Action_UP event from onFlingListener, but when i drag very slowly，I can't receive Action_UP event，And i dont know where i can get that Action_UP event. Hoping for reply

**Comment by simonhjq2014** [comment]
i found set manifest Activity this ： android:hardwareAccelerated="true"。 better

**Comment by luckysmg** [comment]
ok i will try it ,thx
