### ISSUE TITLE
setScale focal x and y odd behavior on CenterCrop image scaling?

### ISSUE THREAD

**Issue by arsonistAnt** [chrisbanes/PhotoView#734]
Hi all,

Basically what I'm trying to do is to bring my image focal point to the top of the image after its zoomed in. For some reason when I try setting the focalX & focalY with setScale it seems to just end up at the center of the image instead.

The height of my image is larger vertically & I set the photo view scaling to `centerCrop`

Here is the code below I used:
`photoView.setScale(1.0f,0f,0f,false)`

Any tips?

**Comment by arsonistAnt** [comment]
Decided to fork and modify the repo instead, if anyone needs it you can find it [here].(https://github.com/arsonistAnt/PhotoView/commit/62f96ad6d0e694a2da802998f551f6d8979c969b)

**Comment by andysagar** [comment]
menu_matrix_restore and menu_matrix_capture is not working properly after applying center crop on portrait image

**Comment by arsonistAnt** [comment]
Hmm, I've only modified the behaviors when you apply the "autoScaleWidth" custom attribute. Have you tried this without my modifications?
