### ISSUE TITLE
After apply new bitmap how can i restore old scale and image x y value?

### ISSUE THREAD

**Issue by andysagar** [chrisbanes/PhotoView#738]
When i change bitmap of image after doing some zoom and drag. how can i restore it same zoom and x y value of image ?

i tried this method to restore it. Imagescale is working fine but x and y value is not working currently

 main_img.getAttacher()
                        .setScale(scalevalue,
                                sx,
                                sy,
                                false);

**Comment by tolik85** [comment]
did you find a solution?
