### ISSUE TITLE
Save Image after zoom/drag

### ISSUE THREAD

**Issue by AhmadIzaz** [chrisbanes/PhotoView#763]
I want to save the image after being zoomed or dragged. e.g I have an image I double tapped on it and it got zoomed, now I wan to save that zoomed part of image that is being display on my screen currently. How can I do that.
I couldn't find any method to get the zoomed or dragged image.

P.S : It will be great if you add these type of function to get the zoomed/dragged bitmap/drawable so one can just call the function and get the image to save it and reuse it later.

**Comment by kiranofans** [comment]
> I want to save the image after being zoomed or dragged. e.g I have an image I double tapped on it and it got zoomed, now I wan to save that zoomed part of image that is being display on my screen currently. How can I do that.
> I couldn't find any method to get the zoomed or dragged image.
> 
> P.S : It will be great if you add these type of function to get the zoomed/dragged bitmap/drawable so one can just call the function and get the image to save it and reuse it later.
In my opinion, the basic logic to implement this feature is to capture the zoomed part (this will be another image file), then save the image to somewhere local
I think you can google how to programmatically make a screenshot feature in android or ios or whatever.

**Comment by AhmadIzaz** [comment]
@kiranofans we cant screenshot here as we are using this as a wallpaper means the zoomed image is in background and contains multiple above than that, If we screenshot, we capture these views too which we dont want.

**Comment by AhmadIzaz** [comment]
Infact, this is what I did to solve the problem.

public void save() {
        try {
            Bitmap returnedBitmap = Bitmap.createBitmap(
                    mPhotoView.getWidth(),
                    mPhotoView.getHeight(),
                    Bitmap.Config.ARGB_8888);
            Canvas canvas = new Canvas(returnedBitmap);

            Drawable bgDrawable = mPhotoView.getDrawable();

            if (bgDrawable != null)
                bgDrawable.draw(canvas);
            else
                canvas.drawColor(Color.WHITE);

            mPhotoView.draw(canvas);

            ByteArrayOutputStream bs = new ByteArrayOutputStream();
            returnedBitmap.compress(Bitmap.CompressFormat.PNG, 100, bs);

            Bitmap FinalBitmap = BitmapFactory.decodeByteArray(bs.toByteArray(), 0,
                    bs.toByteArray().length);

            mPhotoView.setImageBitmap(FinalBitmap );
            
     
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
