### ISSUE TITLE
show the image its height is very big

### ISSUE THREAD

**Issue by denny37** [chrisbanes/PhotoView#85]
for example the image's height 14000px, but its width only is 600px,
if compress, the image can't to see clearly,
so, how to do this.
can use BitmapRegionDecoder to realize?

**Comment by yorkwang** [comment]
Any update?

**Comment by Jawnnypoo** [comment]
This goes beyond the scope of this library, which does not provide subsampling. See this library as an alternative
https://github.com/davemorrissey/subsampling-scale-image-view
