### ISSUE TITLE
ImageView inside ViewPager ignores layout params

### ISSUE THREAD

**Issue by pfives** [chrisbanes/PhotoView#99]
I have an ImageView in a fragment hosted by a view pager. The fragment layout is a RelativeLayout and the ImageView is centerPositioned inside of it. When I initialize the PhotoAttacher with the ImageView the image starts at the top of the screen instead of in the center of the screen. If I touch and drag a tiny bit in any direction the image immediately snaps into place. The image is loaded dynamically from the web if that is useful.

**Comment by darzul** [comment]
Same here !

**Comment by riinav** [comment]
same here, cant understand how to solve this issue. In my case the Image is displayed near bottom right corner, no matter any size.

however if I disable zoom, the Image is properly displayed in the center of the Screen

**Comment by brentwatson** [comment]
Hope this helps somebody...

I had this same problem when using Picasso.  The solution for me was to make sure `PhotoViewAttacher#update()` is called after the image is done loading.

Eg, converted this:

```java
Picasso.with(context)
    .load(url)
    .fit()
    .centerInside()
    .into(imageView);

new PhotoViewAttacher(imageView);
```

To this:

```java
final PhotoViewAttacher photoViewAttacher = new PhotoViewAttacher(imageView);

Picasso.with(context)
    .load(url)
    .fit()
    .centerInside()
    .into(imageView, new Callback() {
        @Override
        public void onSuccess() {
            photoViewAttacher.update();
        }
        
        @Override
        public void onError() { }
    });
```

**Comment by Jawnnypoo** [comment]
@brentwatson Good catch and solution there. Might be a good thing to consider putting in the README.

**Comment by danieljonker** [comment]
On glide to get around this issue, the same solution didn't work with their listener callbacks. Instead I had to disable zoom, then re-enable it in the resourceready callback.

```
final PhotoViewAttacher attacher = new PhotoViewAttacher(imageView);
attacher.setZoomable(false);
imageHelper.loadImageInView(url, imageView, imageType, attacher);
```

```
Glide.with(imageView.getContext()).load(url)
                .listener(new RequestListener<String, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, String model, Target<GlideDrawable> target, boolean isFirstResource) {
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, String model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        attacher.setZoomable(true);
                        return false;
                    }
                })
                .into(imageView);
```

**Comment by JAgostoni** [comment]
@danieljonker great find on Glide! Worked like a charm!

**Comment by danieljonker** [comment]
@JAgostoni I just edited the above code snippet, you also need to tell glide to request the original sized image with:
```.override(Target.SIZE_ORIGINAL, Target.SIZE_ORIGINAL)```

**Comment by JAgostoni** [comment]
@danieljonker thanks.  I added that and did notice any changes.  What did that do for you?

**Comment by danieljonker** [comment]
@JAgostoni Glide downsizes the image based on your imageview size, So if you're wanting to zoom in with Photoview your image will be as big as the imageview. So zooming will cause it to be blurry.

**Comment by JAgostoni** [comment]
Thanks, @danieljonker.  Probably just coincidental that my images were sized close enough!

**Comment by Jawnnypoo** [comment]
Added to the sample. Thanks!

**Comment by rezool94** [comment]
@danieljonker Thanks you rocked!
